# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bus.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tbus.proto\x12\x06osprey\x1a\x1b\x62uf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf8\x01\n\rFirehoseEvent\x12\x18\n\x03\x64id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03\x64id\x12@\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\ttimestamp\x12-\n\x04kind\x18\x03 \x01(\x0e\x32\x11.osprey.EventKindB\x06\xbaH\x03\xc8\x01\x01R\x04kind\x12&\n\x06\x63ommit\x18\x04 \x01(\x0b\x32\x0e.osprey.CommitR\x06\x63ommit\x12\x18\n\x07\x61\x63\x63ount\x18\x05 \x01(\x0cR\x07\x61\x63\x63ount\x12\x1a\n\x08identity\x18\x06 \x01(\x0cR\x08identity\"\xaf\x01\n\x06\x43ommit\x12\x10\n\x03rev\x18\x01 \x01(\tR\x03rev\x12\x35\n\toperation\x18\x02 \x01(\x0e\x32\x17.osprey.CommitOperationR\toperation\x12\x1e\n\ncollection\x18\x03 \x01(\tR\ncollection\x12\x12\n\x04rkey\x18\x04 \x01(\tR\x04rkey\x12\x16\n\x06record\x18\x05 \x01(\x0cR\x06record\x12\x10\n\x03\x63id\x18\x06 \x01(\tR\x03\x63id\"H\n\x06\x43ursor\x12\x1a\n\x08sequence\x18\x01 \x01(\x03R\x08sequence\x12\"\n\rsaved_on_exit\x18\x02 \x01(\x08R\x0bsavedOnExit*o\n\tEventKind\x12\x1a\n\x16\x45VENT_KIND_UNSPECIFIED\x10\x00\x12\x15\n\x11\x45VENT_KIND_COMMIT\x10\x01\x12\x16\n\x12\x45VENT_KIND_ACCOUNT\x10\x02\x12\x17\n\x13\x45VENT_KIND_IDENTITY\x10\x03*\x8a\x01\n\x0f\x43ommitOperation\x12 \n\x1c\x43OMMIT_OPERATION_UNSPECIFIED\x10\x00\x12\x1b\n\x17\x43OMMIT_OPERATION_CREATE\x10\x01\x12\x1b\n\x17\x43OMMIT_OPERATION_UPDATE\x10\x02\x12\x1b\n\x17\x43OMMIT_OPERATION_DELETE\x10\x03\x42X\n\ncom.ospreyB\x08\x42usProtoP\x01Z\x08/;osprey\xa2\x02\x03OXX\xaa\x02\x06Osprey\xca\x02\x06Osprey\xe2\x02\x12Osprey\\GPBMetadata\xea\x02\x06Ospreyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\ncom.ospreyB\010BusProtoP\001Z\010/;osprey\242\002\003OXX\252\002\006Osprey\312\002\006Osprey\342\002\022Osprey\\GPBMetadata\352\002\006Osprey'
  _globals['_FIREHOSEEVENT'].fields_by_name['did']._loaded_options = None
  _globals['_FIREHOSEEVENT'].fields_by_name['did']._serialized_options = b'\272H\003\310\001\001'
  _globals['_FIREHOSEEVENT'].fields_by_name['timestamp']._loaded_options = None
  _globals['_FIREHOSEEVENT'].fields_by_name['timestamp']._serialized_options = b'\272H\003\310\001\001'
  _globals['_FIREHOSEEVENT'].fields_by_name['kind']._loaded_options = None
  _globals['_FIREHOSEEVENT'].fields_by_name['kind']._serialized_options = b'\272H\003\310\001\001'
  _globals['_EVENTKIND']._serialized_start=586
  _globals['_EVENTKIND']._serialized_end=697
  _globals['_COMMITOPERATION']._serialized_start=700
  _globals['_COMMITOPERATION']._serialized_end=838
  _globals['_FIREHOSEEVENT']._serialized_start=84
  _globals['_FIREHOSEEVENT']._serialized_end=332
  _globals['_COMMIT']._serialized_start=335
  _globals['_COMMIT']._serialized_end=510
  _globals['_CURSOR']._serialized_start=512
  _globals['_CURSOR']._serialized_end=584
# @@protoc_insertion_point(module_scope)
