// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: osprey_atproto.proto

// Implements types for the Bufsteam demo.

package osprey

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AtprotoSubjectKind int32

const (
	AtprotoSubjectKind_ATPROTO_SUBJECT_KIND_NONE   AtprotoSubjectKind = 0
	AtprotoSubjectKind_ATPROTO_SUBJECT_KIND_ACTOR  AtprotoSubjectKind = 1
	AtprotoSubjectKind_ATPROTO_SUBJECT_KIND_RECORD AtprotoSubjectKind = 2
)

// Enum value maps for AtprotoSubjectKind.
var (
	AtprotoSubjectKind_name = map[int32]string{
		0: "ATPROTO_SUBJECT_KIND_NONE",
		1: "ATPROTO_SUBJECT_KIND_ACTOR",
		2: "ATPROTO_SUBJECT_KIND_RECORD",
	}
	AtprotoSubjectKind_value = map[string]int32{
		"ATPROTO_SUBJECT_KIND_NONE":   0,
		"ATPROTO_SUBJECT_KIND_ACTOR":  1,
		"ATPROTO_SUBJECT_KIND_RECORD": 2,
	}
)

func (x AtprotoSubjectKind) Enum() *AtprotoSubjectKind {
	p := new(AtprotoSubjectKind)
	*p = x
	return p
}

func (x AtprotoSubjectKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AtprotoSubjectKind) Descriptor() protoreflect.EnumDescriptor {
	return file_osprey_atproto_proto_enumTypes[0].Descriptor()
}

func (AtprotoSubjectKind) Type() protoreflect.EnumType {
	return &file_osprey_atproto_proto_enumTypes[0]
}

func (x AtprotoSubjectKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AtprotoSubjectKind.Descriptor instead.
func (AtprotoSubjectKind) EnumDescriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{0}
}

type AtprotoLabel int32

const (
	AtprotoLabel_ATPROTO_LABEL_NONE         AtprotoLabel = 0
	AtprotoLabel_ATPROTO_LABEL_SPAM         AtprotoLabel = 1
	AtprotoLabel_ATPROTO_LABEL_RUDE         AtprotoLabel = 2
	AtprotoLabel_ATPROTO_LABEL_PORN         AtprotoLabel = 3
	AtprotoLabel_ATPROTO_LABEL_SEXUAL       AtprotoLabel = 4
	AtprotoLabel_ATPROTO_LABEL_WARN         AtprotoLabel = 5
	AtprotoLabel_ATPROTO_LABEL_HIDE         AtprotoLabel = 6
	AtprotoLabel_ATPROTO_LABEL_NEEDS_REVIEW AtprotoLabel = 7
	AtprotoLabel_ATPROTO_LABEL_MISLEADING   AtprotoLabel = 8
)

// Enum value maps for AtprotoLabel.
var (
	AtprotoLabel_name = map[int32]string{
		0: "ATPROTO_LABEL_NONE",
		1: "ATPROTO_LABEL_SPAM",
		2: "ATPROTO_LABEL_RUDE",
		3: "ATPROTO_LABEL_PORN",
		4: "ATPROTO_LABEL_SEXUAL",
		5: "ATPROTO_LABEL_WARN",
		6: "ATPROTO_LABEL_HIDE",
		7: "ATPROTO_LABEL_NEEDS_REVIEW",
		8: "ATPROTO_LABEL_MISLEADING",
	}
	AtprotoLabel_value = map[string]int32{
		"ATPROTO_LABEL_NONE":         0,
		"ATPROTO_LABEL_SPAM":         1,
		"ATPROTO_LABEL_RUDE":         2,
		"ATPROTO_LABEL_PORN":         3,
		"ATPROTO_LABEL_SEXUAL":       4,
		"ATPROTO_LABEL_WARN":         5,
		"ATPROTO_LABEL_HIDE":         6,
		"ATPROTO_LABEL_NEEDS_REVIEW": 7,
		"ATPROTO_LABEL_MISLEADING":   8,
	}
)

func (x AtprotoLabel) Enum() *AtprotoLabel {
	p := new(AtprotoLabel)
	*p = x
	return p
}

func (x AtprotoLabel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AtprotoLabel) Descriptor() protoreflect.EnumDescriptor {
	return file_osprey_atproto_proto_enumTypes[1].Descriptor()
}

func (AtprotoLabel) Type() protoreflect.EnumType {
	return &file_osprey_atproto_proto_enumTypes[1]
}

func (x AtprotoLabel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AtprotoLabel.Descriptor instead.
func (AtprotoLabel) EnumDescriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{1}
}

type AtprotoEffectKind int32

const (
	AtprotoEffectKind_ATPROTO_EFFECT_KIND_NONE   AtprotoEffectKind = 0
	AtprotoEffectKind_ATPROTO_EFFECT_KIND_ADD    AtprotoEffectKind = 1
	AtprotoEffectKind_ATPROTO_EFFECT_KIND_REMOVE AtprotoEffectKind = 2
)

// Enum value maps for AtprotoEffectKind.
var (
	AtprotoEffectKind_name = map[int32]string{
		0: "ATPROTO_EFFECT_KIND_NONE",
		1: "ATPROTO_EFFECT_KIND_ADD",
		2: "ATPROTO_EFFECT_KIND_REMOVE",
	}
	AtprotoEffectKind_value = map[string]int32{
		"ATPROTO_EFFECT_KIND_NONE":   0,
		"ATPROTO_EFFECT_KIND_ADD":    1,
		"ATPROTO_EFFECT_KIND_REMOVE": 2,
	}
)

func (x AtprotoEffectKind) Enum() *AtprotoEffectKind {
	p := new(AtprotoEffectKind)
	*p = x
	return p
}

func (x AtprotoEffectKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AtprotoEffectKind) Descriptor() protoreflect.EnumDescriptor {
	return file_osprey_atproto_proto_enumTypes[2].Descriptor()
}

func (AtprotoEffectKind) Type() protoreflect.EnumType {
	return &file_osprey_atproto_proto_enumTypes[2]
}

func (x AtprotoEffectKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AtprotoEffectKind.Descriptor instead.
func (AtprotoEffectKind) EnumDescriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{2}
}

type AtprotoEmail int32

const (
	AtprotoEmail_ATPROTO_EMAIL_NONE                  AtprotoEmail = 0
	AtprotoEmail_ATPROTO_EMAIL_SPAM_REPLY            AtprotoEmail = 68
	AtprotoEmail_ATPROTO_EMAIL_SPAM_TAKEDOWN         AtprotoEmail = 261
	AtprotoEmail_ATPROTO_EMAIL_SPAM_FAKE             AtprotoEmail = 63
	AtprotoEmail_ATPROTO_EMAIL_SPAM_LABEL            AtprotoEmail = 318
	AtprotoEmail_ATPROTO_EMAIL_SPAM_LABEL_24_HOURS   AtprotoEmail = 302
	AtprotoEmail_ATPROTO_EMAIL_SPAM_LABEL_72_HOURS   AtprotoEmail = 313
	AtprotoEmail_ATPROTO_EMAIL_ID_REQUEST            AtprotoEmail = 281
	AtprotoEmail_ATPROTO_EMAIL_IMPERSONATION_LABEL   AtprotoEmail = 31
	AtprotoEmail_ATPROTO_EMAIL_AUTOMOD_TAKEDOWN      AtprotoEmail = 288
	AtprotoEmail_ATPROTO_EMAIL_REINSTATEMENT         AtprotoEmail = 60
	AtprotoEmail_ATPROTO_EMAIL_THREAT_POST_TAKEDOWN  AtprotoEmail = 26
	AtprotoEmail_ATPROTO_EMAIL_PEDO_ACCOUNT_TAKEDOWN AtprotoEmail = 43
	AtprotoEmail_ATPROTO_EMAIL_DMS_DISABLED          AtprotoEmail = 295
	AtprotoEmail_ATPROTO_EMAIL_TOXIC_LIST_HIDE       AtprotoEmail = 51
)

// Enum value maps for AtprotoEmail.
var (
	AtprotoEmail_name = map[int32]string{
		0:   "ATPROTO_EMAIL_NONE",
		68:  "ATPROTO_EMAIL_SPAM_REPLY",
		261: "ATPROTO_EMAIL_SPAM_TAKEDOWN",
		63:  "ATPROTO_EMAIL_SPAM_FAKE",
		318: "ATPROTO_EMAIL_SPAM_LABEL",
		302: "ATPROTO_EMAIL_SPAM_LABEL_24_HOURS",
		313: "ATPROTO_EMAIL_SPAM_LABEL_72_HOURS",
		281: "ATPROTO_EMAIL_ID_REQUEST",
		31:  "ATPROTO_EMAIL_IMPERSONATION_LABEL",
		288: "ATPROTO_EMAIL_AUTOMOD_TAKEDOWN",
		60:  "ATPROTO_EMAIL_REINSTATEMENT",
		26:  "ATPROTO_EMAIL_THREAT_POST_TAKEDOWN",
		43:  "ATPROTO_EMAIL_PEDO_ACCOUNT_TAKEDOWN",
		295: "ATPROTO_EMAIL_DMS_DISABLED",
		51:  "ATPROTO_EMAIL_TOXIC_LIST_HIDE",
	}
	AtprotoEmail_value = map[string]int32{
		"ATPROTO_EMAIL_NONE":                  0,
		"ATPROTO_EMAIL_SPAM_REPLY":            68,
		"ATPROTO_EMAIL_SPAM_TAKEDOWN":         261,
		"ATPROTO_EMAIL_SPAM_FAKE":             63,
		"ATPROTO_EMAIL_SPAM_LABEL":            318,
		"ATPROTO_EMAIL_SPAM_LABEL_24_HOURS":   302,
		"ATPROTO_EMAIL_SPAM_LABEL_72_HOURS":   313,
		"ATPROTO_EMAIL_ID_REQUEST":            281,
		"ATPROTO_EMAIL_IMPERSONATION_LABEL":   31,
		"ATPROTO_EMAIL_AUTOMOD_TAKEDOWN":      288,
		"ATPROTO_EMAIL_REINSTATEMENT":         60,
		"ATPROTO_EMAIL_THREAT_POST_TAKEDOWN":  26,
		"ATPROTO_EMAIL_PEDO_ACCOUNT_TAKEDOWN": 43,
		"ATPROTO_EMAIL_DMS_DISABLED":          295,
		"ATPROTO_EMAIL_TOXIC_LIST_HIDE":       51,
	}
)

func (x AtprotoEmail) Enum() *AtprotoEmail {
	p := new(AtprotoEmail)
	*p = x
	return p
}

func (x AtprotoEmail) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AtprotoEmail) Descriptor() protoreflect.EnumDescriptor {
	return file_osprey_atproto_proto_enumTypes[3].Descriptor()
}

func (AtprotoEmail) Type() protoreflect.EnumType {
	return &file_osprey_atproto_proto_enumTypes[3]
}

func (x AtprotoEmail) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AtprotoEmail.Descriptor instead.
func (AtprotoEmail) EnumDescriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{3}
}

type AtprotoReportKind int32

const (
	AtprotoReportKind_ATPROTO_REPORT_KIND_NONE       AtprotoReportKind = 0
	AtprotoReportKind_ATPROTO_REPORT_KIND_SPAM       AtprotoReportKind = 1
	AtprotoReportKind_ATPROTO_REPORT_KIND_VIOLATION  AtprotoReportKind = 2
	AtprotoReportKind_ATPROTO_REPORT_KIND_MISLEADING AtprotoReportKind = 3
	AtprotoReportKind_ATPROTO_REPORT_KIND_SEXUAL     AtprotoReportKind = 4
	AtprotoReportKind_ATPROTO_REPORT_KIND_RUDE       AtprotoReportKind = 5
	AtprotoReportKind_ATPROTO_REPORT_KIND_OTHER      AtprotoReportKind = 6
)

// Enum value maps for AtprotoReportKind.
var (
	AtprotoReportKind_name = map[int32]string{
		0: "ATPROTO_REPORT_KIND_NONE",
		1: "ATPROTO_REPORT_KIND_SPAM",
		2: "ATPROTO_REPORT_KIND_VIOLATION",
		3: "ATPROTO_REPORT_KIND_MISLEADING",
		4: "ATPROTO_REPORT_KIND_SEXUAL",
		5: "ATPROTO_REPORT_KIND_RUDE",
		6: "ATPROTO_REPORT_KIND_OTHER",
	}
	AtprotoReportKind_value = map[string]int32{
		"ATPROTO_REPORT_KIND_NONE":       0,
		"ATPROTO_REPORT_KIND_SPAM":       1,
		"ATPROTO_REPORT_KIND_VIOLATION":  2,
		"ATPROTO_REPORT_KIND_MISLEADING": 3,
		"ATPROTO_REPORT_KIND_SEXUAL":     4,
		"ATPROTO_REPORT_KIND_RUDE":       5,
		"ATPROTO_REPORT_KIND_OTHER":      6,
	}
)

func (x AtprotoReportKind) Enum() *AtprotoReportKind {
	p := new(AtprotoReportKind)
	*p = x
	return p
}

func (x AtprotoReportKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AtprotoReportKind) Descriptor() protoreflect.EnumDescriptor {
	return file_osprey_atproto_proto_enumTypes[4].Descriptor()
}

func (AtprotoReportKind) Type() protoreflect.EnumType {
	return &file_osprey_atproto_proto_enumTypes[4]
}

func (x AtprotoReportKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AtprotoReportKind.Descriptor instead.
func (AtprotoReportKind) EnumDescriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{4}
}

// Enums for the constants (optional, but recommended for type safety)
type EventKind int32

const (
	EventKind_EVENT_KIND_UNSPECIFIED EventKind = 0
	EventKind_EVENT_KIND_COMMIT      EventKind = 1
	EventKind_EVENT_KIND_ACCOUNT     EventKind = 2
	EventKind_EVENT_KIND_IDENTITY    EventKind = 3
)

// Enum value maps for EventKind.
var (
	EventKind_name = map[int32]string{
		0: "EVENT_KIND_UNSPECIFIED",
		1: "EVENT_KIND_COMMIT",
		2: "EVENT_KIND_ACCOUNT",
		3: "EVENT_KIND_IDENTITY",
	}
	EventKind_value = map[string]int32{
		"EVENT_KIND_UNSPECIFIED": 0,
		"EVENT_KIND_COMMIT":      1,
		"EVENT_KIND_ACCOUNT":     2,
		"EVENT_KIND_IDENTITY":    3,
	}
)

func (x EventKind) Enum() *EventKind {
	p := new(EventKind)
	*p = x
	return p
}

func (x EventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_osprey_atproto_proto_enumTypes[5].Descriptor()
}

func (EventKind) Type() protoreflect.EnumType {
	return &file_osprey_atproto_proto_enumTypes[5]
}

func (x EventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventKind.Descriptor instead.
func (EventKind) EnumDescriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{5}
}

type CommitOperation int32

const (
	CommitOperation_COMMIT_OPERATION_UNSPECIFIED CommitOperation = 0
	CommitOperation_COMMIT_OPERATION_CREATE      CommitOperation = 1
	CommitOperation_COMMIT_OPERATION_UPDATE      CommitOperation = 2
	CommitOperation_COMMIT_OPERATION_DELETE      CommitOperation = 3
)

// Enum value maps for CommitOperation.
var (
	CommitOperation_name = map[int32]string{
		0: "COMMIT_OPERATION_UNSPECIFIED",
		1: "COMMIT_OPERATION_CREATE",
		2: "COMMIT_OPERATION_UPDATE",
		3: "COMMIT_OPERATION_DELETE",
	}
	CommitOperation_value = map[string]int32{
		"COMMIT_OPERATION_UNSPECIFIED": 0,
		"COMMIT_OPERATION_CREATE":      1,
		"COMMIT_OPERATION_UPDATE":      2,
		"COMMIT_OPERATION_DELETE":      3,
	}
)

func (x CommitOperation) Enum() *CommitOperation {
	p := new(CommitOperation)
	*p = x
	return p
}

func (x CommitOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommitOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_osprey_atproto_proto_enumTypes[6].Descriptor()
}

func (CommitOperation) Type() protoreflect.EnumType {
	return &file_osprey_atproto_proto_enumTypes[6]
}

func (x CommitOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommitOperation.Descriptor instead.
func (CommitOperation) EnumDescriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{6}
}

type OspreyInputEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *OspreyInputEventData  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	SendTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OspreyInputEvent) Reset() {
	*x = OspreyInputEvent{}
	mi := &file_osprey_atproto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OspreyInputEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OspreyInputEvent) ProtoMessage() {}

func (x *OspreyInputEvent) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OspreyInputEvent.ProtoReflect.Descriptor instead.
func (*OspreyInputEvent) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{0}
}

func (x *OspreyInputEvent) GetData() *OspreyInputEventData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *OspreyInputEvent) GetSendTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SendTime
	}
	return nil
}

type OspreyInputEventData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionName    string                 `protobuf:"bytes,1,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`
	ActionId      int64                  `protobuf:"varint,2,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SecretData    map[string]string      `protobuf:"bytes,5,rep,name=secret_data,json=secretData,proto3" json:"secret_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Encoding      string                 `protobuf:"bytes,6,opt,name=encoding,proto3" json:"encoding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OspreyInputEventData) Reset() {
	*x = OspreyInputEventData{}
	mi := &file_osprey_atproto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OspreyInputEventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OspreyInputEventData) ProtoMessage() {}

func (x *OspreyInputEventData) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OspreyInputEventData.ProtoReflect.Descriptor instead.
func (*OspreyInputEventData) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{1}
}

func (x *OspreyInputEventData) GetActionName() string {
	if x != nil {
		return x.ActionName
	}
	return ""
}

func (x *OspreyInputEventData) GetActionId() int64 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

func (x *OspreyInputEventData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *OspreyInputEventData) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *OspreyInputEventData) GetSecretData() map[string]string {
	if x != nil {
		return x.SecretData
	}
	return nil
}

func (x *OspreyInputEventData) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

type AtprotoLabelEffect struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EffectKind        AtprotoEffectKind      `protobuf:"varint,1,opt,name=effect_kind,json=effectKind,proto3,enum=osprey.AtprotoEffectKind" json:"effect_kind,omitempty"`
	SubjectKind       AtprotoSubjectKind     `protobuf:"varint,2,opt,name=subject_kind,json=subjectKind,proto3,enum=osprey.AtprotoSubjectKind" json:"subject_kind,omitempty"`
	Label             AtprotoLabel           `protobuf:"varint,3,opt,name=label,proto3,enum=osprey.AtprotoLabel" json:"label,omitempty"`
	Comment           string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	Email             *AtprotoEmail          `protobuf:"varint,5,opt,name=email,proto3,enum=osprey.AtprotoEmail,oneof" json:"email,omitempty"`
	ExpirationInHours *int64                 `protobuf:"varint,6,opt,name=expiration_in_hours,json=expirationInHours,proto3,oneof" json:"expiration_in_hours,omitempty"`
	Rules             []string               `protobuf:"bytes,7,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AtprotoLabelEffect) Reset() {
	*x = AtprotoLabelEffect{}
	mi := &file_osprey_atproto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtprotoLabelEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtprotoLabelEffect) ProtoMessage() {}

func (x *AtprotoLabelEffect) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtprotoLabelEffect.ProtoReflect.Descriptor instead.
func (*AtprotoLabelEffect) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{2}
}

func (x *AtprotoLabelEffect) GetEffectKind() AtprotoEffectKind {
	if x != nil {
		return x.EffectKind
	}
	return AtprotoEffectKind_ATPROTO_EFFECT_KIND_NONE
}

func (x *AtprotoLabelEffect) GetSubjectKind() AtprotoSubjectKind {
	if x != nil {
		return x.SubjectKind
	}
	return AtprotoSubjectKind_ATPROTO_SUBJECT_KIND_NONE
}

func (x *AtprotoLabelEffect) GetLabel() AtprotoLabel {
	if x != nil {
		return x.Label
	}
	return AtprotoLabel_ATPROTO_LABEL_NONE
}

func (x *AtprotoLabelEffect) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *AtprotoLabelEffect) GetEmail() AtprotoEmail {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return AtprotoEmail_ATPROTO_EMAIL_NONE
}

func (x *AtprotoLabelEffect) GetExpirationInHours() int64 {
	if x != nil && x.ExpirationInHours != nil {
		return *x.ExpirationInHours
	}
	return 0
}

func (x *AtprotoLabelEffect) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

type AtprotoTagEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EffectKind    AtprotoEffectKind      `protobuf:"varint,1,opt,name=effect_kind,json=effectKind,proto3,enum=osprey.AtprotoEffectKind" json:"effect_kind,omitempty"`
	SubjectKind   AtprotoSubjectKind     `protobuf:"varint,2,opt,name=subject_kind,json=subjectKind,proto3,enum=osprey.AtprotoSubjectKind" json:"subject_kind,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Comment       *string                `protobuf:"bytes,4,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	Rules         []string               `protobuf:"bytes,5,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtprotoTagEffect) Reset() {
	*x = AtprotoTagEffect{}
	mi := &file_osprey_atproto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtprotoTagEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtprotoTagEffect) ProtoMessage() {}

func (x *AtprotoTagEffect) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtprotoTagEffect.ProtoReflect.Descriptor instead.
func (*AtprotoTagEffect) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{3}
}

func (x *AtprotoTagEffect) GetEffectKind() AtprotoEffectKind {
	if x != nil {
		return x.EffectKind
	}
	return AtprotoEffectKind_ATPROTO_EFFECT_KIND_NONE
}

func (x *AtprotoTagEffect) GetSubjectKind() AtprotoSubjectKind {
	if x != nil {
		return x.SubjectKind
	}
	return AtprotoSubjectKind_ATPROTO_SUBJECT_KIND_NONE
}

func (x *AtprotoTagEffect) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *AtprotoTagEffect) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

func (x *AtprotoTagEffect) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

type AtprotoTakedownEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EffectKind    AtprotoEffectKind      `protobuf:"varint,1,opt,name=effect_kind,json=effectKind,proto3,enum=osprey.AtprotoEffectKind" json:"effect_kind,omitempty"`
	SubjectKind   AtprotoSubjectKind     `protobuf:"varint,2,opt,name=subject_kind,json=subjectKind,proto3,enum=osprey.AtprotoSubjectKind" json:"subject_kind,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	Email         *AtprotoEmail          `protobuf:"varint,5,opt,name=email,proto3,enum=osprey.AtprotoEmail,oneof" json:"email,omitempty"`
	Rules         []string               `protobuf:"bytes,6,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtprotoTakedownEffect) Reset() {
	*x = AtprotoTakedownEffect{}
	mi := &file_osprey_atproto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtprotoTakedownEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtprotoTakedownEffect) ProtoMessage() {}

func (x *AtprotoTakedownEffect) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtprotoTakedownEffect.ProtoReflect.Descriptor instead.
func (*AtprotoTakedownEffect) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{4}
}

func (x *AtprotoTakedownEffect) GetEffectKind() AtprotoEffectKind {
	if x != nil {
		return x.EffectKind
	}
	return AtprotoEffectKind_ATPROTO_EFFECT_KIND_NONE
}

func (x *AtprotoTakedownEffect) GetSubjectKind() AtprotoSubjectKind {
	if x != nil {
		return x.SubjectKind
	}
	return AtprotoSubjectKind_ATPROTO_SUBJECT_KIND_NONE
}

func (x *AtprotoTakedownEffect) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *AtprotoTakedownEffect) GetEmail() AtprotoEmail {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return AtprotoEmail_ATPROTO_EMAIL_NONE
}

func (x *AtprotoTakedownEffect) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

type AtprotoEmailEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         AtprotoEmail           `protobuf:"varint,1,opt,name=email,proto3,enum=osprey.AtprotoEmail" json:"email,omitempty"`
	Comment       *string                `protobuf:"bytes,2,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	Rules         []string               `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtprotoEmailEffect) Reset() {
	*x = AtprotoEmailEffect{}
	mi := &file_osprey_atproto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtprotoEmailEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtprotoEmailEffect) ProtoMessage() {}

func (x *AtprotoEmailEffect) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtprotoEmailEffect.ProtoReflect.Descriptor instead.
func (*AtprotoEmailEffect) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{5}
}

func (x *AtprotoEmailEffect) GetEmail() AtprotoEmail {
	if x != nil {
		return x.Email
	}
	return AtprotoEmail_ATPROTO_EMAIL_NONE
}

func (x *AtprotoEmailEffect) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

func (x *AtprotoEmailEffect) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

type AtprotoCommentEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectKind   AtprotoSubjectKind     `protobuf:"varint,1,opt,name=subject_kind,json=subjectKind,proto3,enum=osprey.AtprotoSubjectKind" json:"subject_kind,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	Rules         []string               `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtprotoCommentEffect) Reset() {
	*x = AtprotoCommentEffect{}
	mi := &file_osprey_atproto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtprotoCommentEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtprotoCommentEffect) ProtoMessage() {}

func (x *AtprotoCommentEffect) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtprotoCommentEffect.ProtoReflect.Descriptor instead.
func (*AtprotoCommentEffect) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{6}
}

func (x *AtprotoCommentEffect) GetSubjectKind() AtprotoSubjectKind {
	if x != nil {
		return x.SubjectKind
	}
	return AtprotoSubjectKind_ATPROTO_SUBJECT_KIND_NONE
}

func (x *AtprotoCommentEffect) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *AtprotoCommentEffect) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

type AtprotoEscalateEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectKind   AtprotoSubjectKind     `protobuf:"varint,1,opt,name=subject_kind,json=subjectKind,proto3,enum=osprey.AtprotoSubjectKind" json:"subject_kind,omitempty"`
	Comment       *string                `protobuf:"bytes,2,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	Rules         []string               `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtprotoEscalateEffect) Reset() {
	*x = AtprotoEscalateEffect{}
	mi := &file_osprey_atproto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtprotoEscalateEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtprotoEscalateEffect) ProtoMessage() {}

func (x *AtprotoEscalateEffect) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtprotoEscalateEffect.ProtoReflect.Descriptor instead.
func (*AtprotoEscalateEffect) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{7}
}

func (x *AtprotoEscalateEffect) GetSubjectKind() AtprotoSubjectKind {
	if x != nil {
		return x.SubjectKind
	}
	return AtprotoSubjectKind_ATPROTO_SUBJECT_KIND_NONE
}

func (x *AtprotoEscalateEffect) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

func (x *AtprotoEscalateEffect) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

type AtprotoAcknowledgeEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectKind   AtprotoSubjectKind     `protobuf:"varint,1,opt,name=subject_kind,json=subjectKind,proto3,enum=osprey.AtprotoSubjectKind" json:"subject_kind,omitempty"`
	Comment       *string                `protobuf:"bytes,2,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	Rules         []string               `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtprotoAcknowledgeEffect) Reset() {
	*x = AtprotoAcknowledgeEffect{}
	mi := &file_osprey_atproto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtprotoAcknowledgeEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtprotoAcknowledgeEffect) ProtoMessage() {}

func (x *AtprotoAcknowledgeEffect) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtprotoAcknowledgeEffect.ProtoReflect.Descriptor instead.
func (*AtprotoAcknowledgeEffect) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{8}
}

func (x *AtprotoAcknowledgeEffect) GetSubjectKind() AtprotoSubjectKind {
	if x != nil {
		return x.SubjectKind
	}
	return AtprotoSubjectKind_ATPROTO_SUBJECT_KIND_NONE
}

func (x *AtprotoAcknowledgeEffect) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

func (x *AtprotoAcknowledgeEffect) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

type AtprotoReportEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectKind   AtprotoSubjectKind     `protobuf:"varint,1,opt,name=subject_kind,json=subjectKind,proto3,enum=osprey.AtprotoSubjectKind" json:"subject_kind,omitempty"`
	ReportKind    AtprotoReportKind      `protobuf:"varint,2,opt,name=report_kind,json=reportKind,proto3,enum=osprey.AtprotoReportKind" json:"report_kind,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	PriorityScore *int64                 `protobuf:"varint,4,opt,name=priority_score,json=priorityScore,proto3,oneof" json:"priority_score,omitempty"`
	Rules         []string               `protobuf:"bytes,5,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtprotoReportEffect) Reset() {
	*x = AtprotoReportEffect{}
	mi := &file_osprey_atproto_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtprotoReportEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtprotoReportEffect) ProtoMessage() {}

func (x *AtprotoReportEffect) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtprotoReportEffect.ProtoReflect.Descriptor instead.
func (*AtprotoReportEffect) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{9}
}

func (x *AtprotoReportEffect) GetSubjectKind() AtprotoSubjectKind {
	if x != nil {
		return x.SubjectKind
	}
	return AtprotoSubjectKind_ATPROTO_SUBJECT_KIND_NONE
}

func (x *AtprotoReportEffect) GetReportKind() AtprotoReportKind {
	if x != nil {
		return x.ReportKind
	}
	return AtprotoReportKind_ATPROTO_REPORT_KIND_NONE
}

func (x *AtprotoReportEffect) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *AtprotoReportEffect) GetPriorityScore() int64 {
	if x != nil && x.PriorityScore != nil {
		return *x.PriorityScore
	}
	return 0
}

func (x *AtprotoReportEffect) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

type BigQueryFlagEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectKind   AtprotoSubjectKind     `protobuf:"varint,1,opt,name=subject_kind,json=subjectKind,proto3,enum=osprey.AtprotoSubjectKind" json:"subject_kind,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Comment       *string                `protobuf:"bytes,3,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	Rules         []string               `protobuf:"bytes,4,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BigQueryFlagEffect) Reset() {
	*x = BigQueryFlagEffect{}
	mi := &file_osprey_atproto_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BigQueryFlagEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BigQueryFlagEffect) ProtoMessage() {}

func (x *BigQueryFlagEffect) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BigQueryFlagEffect.ProtoReflect.Descriptor instead.
func (*BigQueryFlagEffect) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{10}
}

func (x *BigQueryFlagEffect) GetSubjectKind() AtprotoSubjectKind {
	if x != nil {
		return x.SubjectKind
	}
	return AtprotoSubjectKind_ATPROTO_SUBJECT_KIND_NONE
}

func (x *BigQueryFlagEffect) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *BigQueryFlagEffect) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

func (x *BigQueryFlagEffect) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

type ResultEvent struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	SendTime         *timestamppb.Timestamp      `protobuf:"bytes,1,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	ActionName       string                      `protobuf:"bytes,2,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`
	ActionId         int64                       `protobuf:"varint,3,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Did              string                      `protobuf:"bytes,4,opt,name=did,proto3" json:"did,omitempty"`
	Uri              string                      `protobuf:"bytes,5,opt,name=uri,proto3" json:"uri,omitempty"`
	Cid              string                      `protobuf:"bytes,6,opt,name=cid,proto3" json:"cid,omitempty"`
	Data             []byte                      `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	Labels           []*AtprotoLabelEffect       `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty"`
	Tags             []*AtprotoTagEffect         `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	Takedowns        []*AtprotoTakedownEffect    `protobuf:"bytes,10,rep,name=takedowns,proto3" json:"takedowns,omitempty"`
	Emails           []*AtprotoEmailEffect       `protobuf:"bytes,11,rep,name=emails,proto3" json:"emails,omitempty"`
	Comments         []*AtprotoCommentEffect     `protobuf:"bytes,12,rep,name=comments,proto3" json:"comments,omitempty"`
	Escalations      []*AtprotoEscalateEffect    `protobuf:"bytes,13,rep,name=escalations,proto3" json:"escalations,omitempty"`
	Acknowledgements []*AtprotoAcknowledgeEffect `protobuf:"bytes,14,rep,name=acknowledgements,proto3" json:"acknowledgements,omitempty"`
	Reports          []*AtprotoReportEffect      `protobuf:"bytes,15,rep,name=reports,proto3" json:"reports,omitempty"`
	BigqueryFlags    []*BigQueryFlagEffect       `protobuf:"bytes,16,rep,name=bigqueryFlags,proto3" json:"bigqueryFlags,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResultEvent) Reset() {
	*x = ResultEvent{}
	mi := &file_osprey_atproto_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultEvent) ProtoMessage() {}

func (x *ResultEvent) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultEvent.ProtoReflect.Descriptor instead.
func (*ResultEvent) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{11}
}

func (x *ResultEvent) GetSendTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SendTime
	}
	return nil
}

func (x *ResultEvent) GetActionName() string {
	if x != nil {
		return x.ActionName
	}
	return ""
}

func (x *ResultEvent) GetActionId() int64 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

func (x *ResultEvent) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *ResultEvent) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ResultEvent) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ResultEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ResultEvent) GetLabels() []*AtprotoLabelEffect {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ResultEvent) GetTags() []*AtprotoTagEffect {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ResultEvent) GetTakedowns() []*AtprotoTakedownEffect {
	if x != nil {
		return x.Takedowns
	}
	return nil
}

func (x *ResultEvent) GetEmails() []*AtprotoEmailEffect {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *ResultEvent) GetComments() []*AtprotoCommentEffect {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *ResultEvent) GetEscalations() []*AtprotoEscalateEffect {
	if x != nil {
		return x.Escalations
	}
	return nil
}

func (x *ResultEvent) GetAcknowledgements() []*AtprotoAcknowledgeEffect {
	if x != nil {
		return x.Acknowledgements
	}
	return nil
}

func (x *ResultEvent) GetReports() []*AtprotoReportEffect {
	if x != nil {
		return x.Reports
	}
	return nil
}

func (x *ResultEvent) GetBigqueryFlags() []*BigQueryFlagEffect {
	if x != nil {
		return x.BigqueryFlags
	}
	return nil
}

type FirehoseEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Kind          EventKind              `protobuf:"varint,3,opt,name=kind,proto3,enum=osprey.EventKind" json:"kind,omitempty"`
	Commit        *Commit                `protobuf:"bytes,4,opt,name=commit,proto3" json:"commit,omitempty"`
	Account       []byte                 `protobuf:"bytes,5,opt,name=account,proto3" json:"account,omitempty"`   // comatproto.SyncSubscribeRepos_Account as opaque bytes
	Identity      []byte                 `protobuf:"bytes,6,opt,name=identity,proto3" json:"identity,omitempty"` // comatproto.SyncSubscribeRepos_Identity as opaque bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirehoseEvent) Reset() {
	*x = FirehoseEvent{}
	mi := &file_osprey_atproto_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirehoseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirehoseEvent) ProtoMessage() {}

func (x *FirehoseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirehoseEvent.ProtoReflect.Descriptor instead.
func (*FirehoseEvent) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{12}
}

func (x *FirehoseEvent) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *FirehoseEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *FirehoseEvent) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *FirehoseEvent) GetCommit() *Commit {
	if x != nil {
		return x.Commit
	}
	return nil
}

func (x *FirehoseEvent) GetAccount() []byte {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *FirehoseEvent) GetIdentity() []byte {
	if x != nil {
		return x.Identity
	}
	return nil
}

type Commit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rev           string                 `protobuf:"bytes,1,opt,name=rev,proto3" json:"rev,omitempty"`
	Operation     CommitOperation        `protobuf:"varint,2,opt,name=operation,proto3,enum=osprey.CommitOperation" json:"operation,omitempty"`
	Collection    string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Rkey          string                 `protobuf:"bytes,4,opt,name=rkey,proto3" json:"rkey,omitempty"`
	Record        []byte                 `protobuf:"bytes,5,opt,name=record,proto3" json:"record,omitempty"` // json.RawMessage as opaque bytes
	Cid           string                 `protobuf:"bytes,6,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Commit) Reset() {
	*x = Commit{}
	mi := &file_osprey_atproto_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit.ProtoReflect.Descriptor instead.
func (*Commit) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{13}
}

func (x *Commit) GetRev() string {
	if x != nil {
		return x.Rev
	}
	return ""
}

func (x *Commit) GetOperation() CommitOperation {
	if x != nil {
		return x.Operation
	}
	return CommitOperation_COMMIT_OPERATION_UNSPECIFIED
}

func (x *Commit) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *Commit) GetRkey() string {
	if x != nil {
		return x.Rkey
	}
	return ""
}

func (x *Commit) GetRecord() []byte {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *Commit) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type Cursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      int64                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SavedOnExit   bool                   `protobuf:"varint,2,opt,name=saved_on_exit,json=savedOnExit,proto3" json:"saved_on_exit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cursor) Reset() {
	*x = Cursor{}
	mi := &file_osprey_atproto_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cursor) ProtoMessage() {}

func (x *Cursor) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cursor.ProtoReflect.Descriptor instead.
func (*Cursor) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{14}
}

func (x *Cursor) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Cursor) GetSavedOnExit() bool {
	if x != nil {
		return x.SavedOnExit
	}
	return false
}

type ModerationEnrichedFirehoseRecordEvent struct {
	state               protoimpl.MessageState           `protogen:"open.v1"`
	Did                 string                           `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Timestamp           *timestamppb.Timestamp           `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Collection          string                           `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Rkey                string                           `protobuf:"bytes,4,opt,name=rkey,proto3" json:"rkey,omitempty"`
	Operation           CommitOperation                  `protobuf:"varint,5,opt,name=operation,proto3,enum=osprey.CommitOperation" json:"operation,omitempty"`
	Record              []byte                           `protobuf:"bytes,6,opt,name=record,proto3" json:"record,omitempty"`                                                                                                           // json.RawMessage as opaque bytes
	ImageResults        map[string]*ImageDispatchResults `protobuf:"bytes,7,rep,name=image_results,json=imageResults,proto3" json:"image_results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // map of image_cid to ImageDispatchResults
	OzoneRepoViewDetail []byte                           `protobuf:"bytes,8,opt,name=ozone_repo_view_detail,json=ozoneRepoViewDetail,proto3,oneof" json:"ozone_repo_view_detail,omitempty"`                                            // JSON encoded repoViewDetail from Ozone for the actor
	DidDoc              []byte                           `protobuf:"bytes,9,opt,name=did_doc,json=didDoc,proto3,oneof" json:"did_doc,omitempty"`                                                                                       // JSON encoded DID Document
	ProfileView         []byte                           `protobuf:"bytes,10,opt,name=profile_view,json=profileView,proto3,oneof" json:"profile_view,omitempty"`                                                                       // JSON encoded ProfileViewDetailed from AppView
	DidAuditLog         []byte                           `protobuf:"bytes,11,opt,name=did_audit_log,json=didAuditLog,proto3,oneof" json:"did_audit_log,omitempty"`                                                                     // JSON encoded DID audit log
	Cid                 string                           `protobuf:"bytes,12,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ModerationEnrichedFirehoseRecordEvent) Reset() {
	*x = ModerationEnrichedFirehoseRecordEvent{}
	mi := &file_osprey_atproto_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModerationEnrichedFirehoseRecordEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModerationEnrichedFirehoseRecordEvent) ProtoMessage() {}

func (x *ModerationEnrichedFirehoseRecordEvent) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModerationEnrichedFirehoseRecordEvent.ProtoReflect.Descriptor instead.
func (*ModerationEnrichedFirehoseRecordEvent) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{15}
}

func (x *ModerationEnrichedFirehoseRecordEvent) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *ModerationEnrichedFirehoseRecordEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ModerationEnrichedFirehoseRecordEvent) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *ModerationEnrichedFirehoseRecordEvent) GetRkey() string {
	if x != nil {
		return x.Rkey
	}
	return ""
}

func (x *ModerationEnrichedFirehoseRecordEvent) GetOperation() CommitOperation {
	if x != nil {
		return x.Operation
	}
	return CommitOperation_COMMIT_OPERATION_UNSPECIFIED
}

func (x *ModerationEnrichedFirehoseRecordEvent) GetRecord() []byte {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *ModerationEnrichedFirehoseRecordEvent) GetImageResults() map[string]*ImageDispatchResults {
	if x != nil {
		return x.ImageResults
	}
	return nil
}

func (x *ModerationEnrichedFirehoseRecordEvent) GetOzoneRepoViewDetail() []byte {
	if x != nil {
		return x.OzoneRepoViewDetail
	}
	return nil
}

func (x *ModerationEnrichedFirehoseRecordEvent) GetDidDoc() []byte {
	if x != nil {
		return x.DidDoc
	}
	return nil
}

func (x *ModerationEnrichedFirehoseRecordEvent) GetProfileView() []byte {
	if x != nil {
		return x.ProfileView
	}
	return nil
}

func (x *ModerationEnrichedFirehoseRecordEvent) GetDidAuditLog() []byte {
	if x != nil {
		return x.DidAuditLog
	}
	return nil
}

func (x *ModerationEnrichedFirehoseRecordEvent) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type ImageDispatchResults struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Cid           string                                  `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Abyss         *ImageDispatchResults_AbyssResults      `protobuf:"bytes,2,opt,name=abyss,proto3,oneof" json:"abyss,omitempty"`
	Hive          *ImageDispatchResults_HiveResults       `protobuf:"bytes,3,opt,name=hive,proto3,oneof" json:"hive,omitempty"`
	Retina        *ImageDispatchResults_RetinaResults     `protobuf:"bytes,4,opt,name=retina,proto3,oneof" json:"retina,omitempty"`
	Prescreen     *ImageDispatchResults_PrescreenResults  `protobuf:"bytes,6,opt,name=prescreen,proto3,oneof" json:"prescreen,omitempty"`
	RetinaHash    *ImageDispatchResults_RetinaHashResults `protobuf:"bytes,7,opt,name=retina_hash,json=retinaHash,proto3,oneof" json:"retina_hash,omitempty"`
	Ncii          *ImageDispatchResults_NciiResults       `protobuf:"bytes,8,opt,name=ncii,proto3,oneof" json:"ncii,omitempty"`
	Flagged       *ImageDispatchResults_FlaggedResults    `protobuf:"bytes,9,opt,name=flagged,proto3,oneof" json:"flagged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageDispatchResults) Reset() {
	*x = ImageDispatchResults{}
	mi := &file_osprey_atproto_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageDispatchResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageDispatchResults) ProtoMessage() {}

func (x *ImageDispatchResults) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageDispatchResults.ProtoReflect.Descriptor instead.
func (*ImageDispatchResults) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{16}
}

func (x *ImageDispatchResults) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ImageDispatchResults) GetAbyss() *ImageDispatchResults_AbyssResults {
	if x != nil {
		return x.Abyss
	}
	return nil
}

func (x *ImageDispatchResults) GetHive() *ImageDispatchResults_HiveResults {
	if x != nil {
		return x.Hive
	}
	return nil
}

func (x *ImageDispatchResults) GetRetina() *ImageDispatchResults_RetinaResults {
	if x != nil {
		return x.Retina
	}
	return nil
}

func (x *ImageDispatchResults) GetPrescreen() *ImageDispatchResults_PrescreenResults {
	if x != nil {
		return x.Prescreen
	}
	return nil
}

func (x *ImageDispatchResults) GetRetinaHash() *ImageDispatchResults_RetinaHashResults {
	if x != nil {
		return x.RetinaHash
	}
	return nil
}

func (x *ImageDispatchResults) GetNcii() *ImageDispatchResults_NciiResults {
	if x != nil {
		return x.Ncii
	}
	return nil
}

func (x *ImageDispatchResults) GetFlagged() *ImageDispatchResults_FlaggedResults {
	if x != nil {
		return x.Flagged
	}
	return nil
}

type ImageDispatchResults_AbyssResults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3,oneof" json:"raw,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	IsAbuseMatch  *bool                  `protobuf:"varint,3,opt,name=is_abuse_match,json=isAbuseMatch,proto3,oneof" json:"is_abuse_match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageDispatchResults_AbyssResults) Reset() {
	*x = ImageDispatchResults_AbyssResults{}
	mi := &file_osprey_atproto_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageDispatchResults_AbyssResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageDispatchResults_AbyssResults) ProtoMessage() {}

func (x *ImageDispatchResults_AbyssResults) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageDispatchResults_AbyssResults.ProtoReflect.Descriptor instead.
func (*ImageDispatchResults_AbyssResults) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{16, 0}
}

func (x *ImageDispatchResults_AbyssResults) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *ImageDispatchResults_AbyssResults) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *ImageDispatchResults_AbyssResults) GetIsAbuseMatch() bool {
	if x != nil && x.IsAbuseMatch != nil {
		return *x.IsAbuseMatch
	}
	return false
}

type ImageDispatchResults_HiveResults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3,oneof" json:"raw,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Classes       map[string]float64     `protobuf:"bytes,3,rep,name=classes,proto3" json:"classes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // map of class name to confidence score
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageDispatchResults_HiveResults) Reset() {
	*x = ImageDispatchResults_HiveResults{}
	mi := &file_osprey_atproto_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageDispatchResults_HiveResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageDispatchResults_HiveResults) ProtoMessage() {}

func (x *ImageDispatchResults_HiveResults) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageDispatchResults_HiveResults.ProtoReflect.Descriptor instead.
func (*ImageDispatchResults_HiveResults) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{16, 1}
}

func (x *ImageDispatchResults_HiveResults) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *ImageDispatchResults_HiveResults) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *ImageDispatchResults_HiveResults) GetClasses() map[string]float64 {
	if x != nil {
		return x.Classes
	}
	return nil
}

type ImageDispatchResults_RetinaResults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3,oneof" json:"raw,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Text          *string                `protobuf:"bytes,3,opt,name=text,proto3,oneof" json:"text,omitempty"` // OCR text result
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageDispatchResults_RetinaResults) Reset() {
	*x = ImageDispatchResults_RetinaResults{}
	mi := &file_osprey_atproto_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageDispatchResults_RetinaResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageDispatchResults_RetinaResults) ProtoMessage() {}

func (x *ImageDispatchResults_RetinaResults) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageDispatchResults_RetinaResults.ProtoReflect.Descriptor instead.
func (*ImageDispatchResults_RetinaResults) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{16, 2}
}

func (x *ImageDispatchResults_RetinaResults) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *ImageDispatchResults_RetinaResults) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *ImageDispatchResults_RetinaResults) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

type ImageDispatchResults_RetinaHashResults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3,oneof" json:"raw,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Hash          *string                `protobuf:"bytes,3,opt,name=hash,proto3,oneof" json:"hash,omitempty"`
	QualityTooLow *bool                  `protobuf:"varint,4,opt,name=quality_too_low,json=qualityTooLow,proto3,oneof" json:"quality_too_low,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageDispatchResults_RetinaHashResults) Reset() {
	*x = ImageDispatchResults_RetinaHashResults{}
	mi := &file_osprey_atproto_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageDispatchResults_RetinaHashResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageDispatchResults_RetinaHashResults) ProtoMessage() {}

func (x *ImageDispatchResults_RetinaHashResults) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageDispatchResults_RetinaHashResults.ProtoReflect.Descriptor instead.
func (*ImageDispatchResults_RetinaHashResults) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{16, 3}
}

func (x *ImageDispatchResults_RetinaHashResults) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *ImageDispatchResults_RetinaHashResults) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *ImageDispatchResults_RetinaHashResults) GetHash() string {
	if x != nil && x.Hash != nil {
		return *x.Hash
	}
	return ""
}

func (x *ImageDispatchResults_RetinaHashResults) GetQualityTooLow() bool {
	if x != nil && x.QualityTooLow != nil {
		return *x.QualityTooLow
	}
	return false
}

type ImageDispatchResults_PrescreenResults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3,oneof" json:"raw,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Decision      *string                `protobuf:"bytes,3,opt,name=decision,proto3,oneof" json:"decision,omitempty"` // "nsfw", "sfw"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageDispatchResults_PrescreenResults) Reset() {
	*x = ImageDispatchResults_PrescreenResults{}
	mi := &file_osprey_atproto_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageDispatchResults_PrescreenResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageDispatchResults_PrescreenResults) ProtoMessage() {}

func (x *ImageDispatchResults_PrescreenResults) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageDispatchResults_PrescreenResults.ProtoReflect.Descriptor instead.
func (*ImageDispatchResults_PrescreenResults) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{16, 4}
}

func (x *ImageDispatchResults_PrescreenResults) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *ImageDispatchResults_PrescreenResults) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *ImageDispatchResults_PrescreenResults) GetDecision() string {
	if x != nil && x.Decision != nil {
		return *x.Decision
	}
	return ""
}

type ImageDispatchResults_NciiResults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3,oneof" json:"raw,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	IsMatch       *bool                  `protobuf:"varint,3,opt,name=is_match,json=isMatch,proto3,oneof" json:"is_match,omitempty"`
	Score         *float64               `protobuf:"fixed64,4,opt,name=score,proto3,oneof" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageDispatchResults_NciiResults) Reset() {
	*x = ImageDispatchResults_NciiResults{}
	mi := &file_osprey_atproto_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageDispatchResults_NciiResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageDispatchResults_NciiResults) ProtoMessage() {}

func (x *ImageDispatchResults_NciiResults) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageDispatchResults_NciiResults.ProtoReflect.Descriptor instead.
func (*ImageDispatchResults_NciiResults) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{16, 5}
}

func (x *ImageDispatchResults_NciiResults) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *ImageDispatchResults_NciiResults) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *ImageDispatchResults_NciiResults) GetIsMatch() bool {
	if x != nil && x.IsMatch != nil {
		return *x.IsMatch
	}
	return false
}

func (x *ImageDispatchResults_NciiResults) GetScore() float64 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

type ImageDispatchResults_FlaggedResults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	IsMatch       *bool                  `protobuf:"varint,2,opt,name=is_match,json=isMatch,proto3,oneof" json:"is_match,omitempty"`
	Action        *string                `protobuf:"bytes,3,opt,name=action,proto3,oneof" json:"action,omitempty"`                              // "tag", "label", "takedown", "report"
	ActionLevel   *string                `protobuf:"bytes,4,opt,name=action_level,json=actionLevel,proto3,oneof" json:"action_level,omitempty"` // "record", "account"
	ActionValue   *string                `protobuf:"bytes,5,opt,name=action_value,json=actionValue,proto3,oneof" json:"action_value,omitempty"`
	AlwaysReport  *bool                  `protobuf:"varint,6,opt,name=always_report,json=alwaysReport,proto3,oneof" json:"always_report,omitempty"`
	Description   *string                `protobuf:"bytes,7,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Score         *float64               `protobuf:"fixed64,8,opt,name=score,proto3,oneof" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageDispatchResults_FlaggedResults) Reset() {
	*x = ImageDispatchResults_FlaggedResults{}
	mi := &file_osprey_atproto_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageDispatchResults_FlaggedResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageDispatchResults_FlaggedResults) ProtoMessage() {}

func (x *ImageDispatchResults_FlaggedResults) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageDispatchResults_FlaggedResults.ProtoReflect.Descriptor instead.
func (*ImageDispatchResults_FlaggedResults) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{16, 6}
}

func (x *ImageDispatchResults_FlaggedResults) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *ImageDispatchResults_FlaggedResults) GetIsMatch() bool {
	if x != nil && x.IsMatch != nil {
		return *x.IsMatch
	}
	return false
}

func (x *ImageDispatchResults_FlaggedResults) GetAction() string {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return ""
}

func (x *ImageDispatchResults_FlaggedResults) GetActionLevel() string {
	if x != nil && x.ActionLevel != nil {
		return *x.ActionLevel
	}
	return ""
}

func (x *ImageDispatchResults_FlaggedResults) GetActionValue() string {
	if x != nil && x.ActionValue != nil {
		return *x.ActionValue
	}
	return ""
}

func (x *ImageDispatchResults_FlaggedResults) GetAlwaysReport() bool {
	if x != nil && x.AlwaysReport != nil {
		return *x.AlwaysReport
	}
	return false
}

func (x *ImageDispatchResults_FlaggedResults) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ImageDispatchResults_FlaggedResults) GetScore() float64 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

var File_osprey_atproto_proto protoreflect.FileDescriptor

const file_osprey_atproto_proto_rawDesc = "" +
	"\n" +
	"\x14osprey_atproto.proto\x12\x06osprey\x1a\x1fgoogle/protobuf/timestamp.proto\"}\n" +
	"\x10OspreyInputEvent\x120\n" +
	"\x04data\x18\x01 \x01(\v2\x1c.osprey.OspreyInputEventDataR\x04data\x127\n" +
	"\tsend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bsendTime\"\xcc\x02\n" +
	"\x14OspreyInputEventData\x12\x1f\n" +
	"\vaction_name\x18\x01 \x01(\tR\n" +
	"actionName\x12\x1b\n" +
	"\taction_id\x18\x02 \x01(\x03R\bactionId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12M\n" +
	"\vsecret_data\x18\x05 \x03(\v2,.osprey.OspreyInputEventData.SecretDataEntryR\n" +
	"secretData\x12\x1a\n" +
	"\bencoding\x18\x06 \x01(\tR\bencoding\x1a=\n" +
	"\x0fSecretDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf3\x02\n" +
	"\x12AtprotoLabelEffect\x12:\n" +
	"\veffect_kind\x18\x01 \x01(\x0e2\x19.osprey.AtprotoEffectKindR\n" +
	"effectKind\x12=\n" +
	"\fsubject_kind\x18\x02 \x01(\x0e2\x1a.osprey.AtprotoSubjectKindR\vsubjectKind\x12*\n" +
	"\x05label\x18\x03 \x01(\x0e2\x14.osprey.AtprotoLabelR\x05label\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12/\n" +
	"\x05email\x18\x05 \x01(\x0e2\x14.osprey.AtprotoEmailH\x00R\x05email\x88\x01\x01\x123\n" +
	"\x13expiration_in_hours\x18\x06 \x01(\x03H\x01R\x11expirationInHours\x88\x01\x01\x12\x14\n" +
	"\x05rules\x18\a \x03(\tR\x05rulesB\b\n" +
	"\x06_emailB\x16\n" +
	"\x14_expiration_in_hours\"\xe0\x01\n" +
	"\x10AtprotoTagEffect\x12:\n" +
	"\veffect_kind\x18\x01 \x01(\x0e2\x19.osprey.AtprotoEffectKindR\n" +
	"effectKind\x12=\n" +
	"\fsubject_kind\x18\x02 \x01(\x0e2\x1a.osprey.AtprotoSubjectKindR\vsubjectKind\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12\x1d\n" +
	"\acomment\x18\x04 \x01(\tH\x00R\acomment\x88\x01\x01\x12\x14\n" +
	"\x05rules\x18\x05 \x03(\tR\x05rulesB\n" +
	"\n" +
	"\b_comment\"\xfd\x01\n" +
	"\x15AtprotoTakedownEffect\x12:\n" +
	"\veffect_kind\x18\x01 \x01(\x0e2\x19.osprey.AtprotoEffectKindR\n" +
	"effectKind\x12=\n" +
	"\fsubject_kind\x18\x02 \x01(\x0e2\x1a.osprey.AtprotoSubjectKindR\vsubjectKind\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12/\n" +
	"\x05email\x18\x05 \x01(\x0e2\x14.osprey.AtprotoEmailH\x00R\x05email\x88\x01\x01\x12\x14\n" +
	"\x05rules\x18\x06 \x03(\tR\x05rulesB\b\n" +
	"\x06_email\"\x81\x01\n" +
	"\x12AtprotoEmailEffect\x12*\n" +
	"\x05email\x18\x01 \x01(\x0e2\x14.osprey.AtprotoEmailR\x05email\x12\x1d\n" +
	"\acomment\x18\x02 \x01(\tH\x00R\acomment\x88\x01\x01\x12\x14\n" +
	"\x05rules\x18\x03 \x03(\tR\x05rulesB\n" +
	"\n" +
	"\b_comment\"\x85\x01\n" +
	"\x14AtprotoCommentEffect\x12=\n" +
	"\fsubject_kind\x18\x01 \x01(\x0e2\x1a.osprey.AtprotoSubjectKindR\vsubjectKind\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12\x14\n" +
	"\x05rules\x18\x03 \x03(\tR\x05rules\"\x97\x01\n" +
	"\x15AtprotoEscalateEffect\x12=\n" +
	"\fsubject_kind\x18\x01 \x01(\x0e2\x1a.osprey.AtprotoSubjectKindR\vsubjectKind\x12\x1d\n" +
	"\acomment\x18\x02 \x01(\tH\x00R\acomment\x88\x01\x01\x12\x14\n" +
	"\x05rules\x18\x03 \x03(\tR\x05rulesB\n" +
	"\n" +
	"\b_comment\"\x9a\x01\n" +
	"\x18AtprotoAcknowledgeEffect\x12=\n" +
	"\fsubject_kind\x18\x01 \x01(\x0e2\x1a.osprey.AtprotoSubjectKindR\vsubjectKind\x12\x1d\n" +
	"\acomment\x18\x02 \x01(\tH\x00R\acomment\x88\x01\x01\x12\x14\n" +
	"\x05rules\x18\x03 \x03(\tR\x05rulesB\n" +
	"\n" +
	"\b_comment\"\xff\x01\n" +
	"\x13AtprotoReportEffect\x12=\n" +
	"\fsubject_kind\x18\x01 \x01(\x0e2\x1a.osprey.AtprotoSubjectKindR\vsubjectKind\x12:\n" +
	"\vreport_kind\x18\x02 \x01(\x0e2\x19.osprey.AtprotoReportKindR\n" +
	"reportKind\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x12*\n" +
	"\x0epriority_score\x18\x04 \x01(\x03H\x00R\rpriorityScore\x88\x01\x01\x12\x14\n" +
	"\x05rules\x18\x05 \x03(\tR\x05rulesB\x11\n" +
	"\x0f_priority_score\"\xa6\x01\n" +
	"\x12BigQueryFlagEffect\x12=\n" +
	"\fsubject_kind\x18\x01 \x01(\x0e2\x1a.osprey.AtprotoSubjectKindR\vsubjectKind\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x1d\n" +
	"\acomment\x18\x03 \x01(\tH\x00R\acomment\x88\x01\x01\x12\x14\n" +
	"\x05rules\x18\x04 \x03(\tR\x05rulesB\n" +
	"\n" +
	"\b_comment\"\xe3\x05\n" +
	"\vResultEvent\x127\n" +
	"\tsend_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bsendTime\x12\x1f\n" +
	"\vaction_name\x18\x02 \x01(\tR\n" +
	"actionName\x12\x1b\n" +
	"\taction_id\x18\x03 \x01(\x03R\bactionId\x12\x10\n" +
	"\x03did\x18\x04 \x01(\tR\x03did\x12\x10\n" +
	"\x03uri\x18\x05 \x01(\tR\x03uri\x12\x10\n" +
	"\x03cid\x18\x06 \x01(\tR\x03cid\x12\x12\n" +
	"\x04data\x18\a \x01(\fR\x04data\x122\n" +
	"\x06labels\x18\b \x03(\v2\x1a.osprey.AtprotoLabelEffectR\x06labels\x12,\n" +
	"\x04tags\x18\t \x03(\v2\x18.osprey.AtprotoTagEffectR\x04tags\x12;\n" +
	"\ttakedowns\x18\n" +
	" \x03(\v2\x1d.osprey.AtprotoTakedownEffectR\ttakedowns\x122\n" +
	"\x06emails\x18\v \x03(\v2\x1a.osprey.AtprotoEmailEffectR\x06emails\x128\n" +
	"\bcomments\x18\f \x03(\v2\x1c.osprey.AtprotoCommentEffectR\bcomments\x12?\n" +
	"\vescalations\x18\r \x03(\v2\x1d.osprey.AtprotoEscalateEffectR\vescalations\x12L\n" +
	"\x10acknowledgements\x18\x0e \x03(\v2 .osprey.AtprotoAcknowledgeEffectR\x10acknowledgements\x125\n" +
	"\areports\x18\x0f \x03(\v2\x1b.osprey.AtprotoReportEffectR\areports\x12@\n" +
	"\rbigqueryFlags\x18\x10 \x03(\v2\x1a.osprey.BigQueryFlagEffectR\rbigqueryFlags\"\xe0\x01\n" +
	"\rFirehoseEvent\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12%\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x11.osprey.EventKindR\x04kind\x12&\n" +
	"\x06commit\x18\x04 \x01(\v2\x0e.osprey.CommitR\x06commit\x12\x18\n" +
	"\aaccount\x18\x05 \x01(\fR\aaccount\x12\x1a\n" +
	"\bidentity\x18\x06 \x01(\fR\bidentity\"\xaf\x01\n" +
	"\x06Commit\x12\x10\n" +
	"\x03rev\x18\x01 \x01(\tR\x03rev\x125\n" +
	"\toperation\x18\x02 \x01(\x0e2\x17.osprey.CommitOperationR\toperation\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12\x12\n" +
	"\x04rkey\x18\x04 \x01(\tR\x04rkey\x12\x16\n" +
	"\x06record\x18\x05 \x01(\fR\x06record\x12\x10\n" +
	"\x03cid\x18\x06 \x01(\tR\x03cid\"H\n" +
	"\x06Cursor\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x03R\bsequence\x12\"\n" +
	"\rsaved_on_exit\x18\x02 \x01(\bR\vsavedOnExit\"\xc0\x05\n" +
	"%ModerationEnrichedFirehoseRecordEvent\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12\x12\n" +
	"\x04rkey\x18\x04 \x01(\tR\x04rkey\x125\n" +
	"\toperation\x18\x05 \x01(\x0e2\x17.osprey.CommitOperationR\toperation\x12\x16\n" +
	"\x06record\x18\x06 \x01(\fR\x06record\x12d\n" +
	"\rimage_results\x18\a \x03(\v2?.osprey.ModerationEnrichedFirehoseRecordEvent.ImageResultsEntryR\fimageResults\x128\n" +
	"\x16ozone_repo_view_detail\x18\b \x01(\fH\x00R\x13ozoneRepoViewDetail\x88\x01\x01\x12\x1c\n" +
	"\adid_doc\x18\t \x01(\fH\x01R\x06didDoc\x88\x01\x01\x12&\n" +
	"\fprofile_view\x18\n" +
	" \x01(\fH\x02R\vprofileView\x88\x01\x01\x12'\n" +
	"\rdid_audit_log\x18\v \x01(\fH\x03R\vdidAuditLog\x88\x01\x01\x12\x10\n" +
	"\x03cid\x18\f \x01(\tR\x03cid\x1a]\n" +
	"\x11ImageResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.osprey.ImageDispatchResultsR\x05value:\x028\x01B\x19\n" +
	"\x17_ozone_repo_view_detailB\n" +
	"\n" +
	"\b_did_docB\x0f\n" +
	"\r_profile_viewB\x10\n" +
	"\x0e_did_audit_log\"\xee\x0f\n" +
	"\x14ImageDispatchResults\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\x12D\n" +
	"\x05abyss\x18\x02 \x01(\v2).osprey.ImageDispatchResults.AbyssResultsH\x00R\x05abyss\x88\x01\x01\x12A\n" +
	"\x04hive\x18\x03 \x01(\v2(.osprey.ImageDispatchResults.HiveResultsH\x01R\x04hive\x88\x01\x01\x12G\n" +
	"\x06retina\x18\x04 \x01(\v2*.osprey.ImageDispatchResults.RetinaResultsH\x02R\x06retina\x88\x01\x01\x12P\n" +
	"\tprescreen\x18\x06 \x01(\v2-.osprey.ImageDispatchResults.PrescreenResultsH\x03R\tprescreen\x88\x01\x01\x12T\n" +
	"\vretina_hash\x18\a \x01(\v2..osprey.ImageDispatchResults.RetinaHashResultsH\x04R\n" +
	"retinaHash\x88\x01\x01\x12A\n" +
	"\x04ncii\x18\b \x01(\v2(.osprey.ImageDispatchResults.NciiResultsH\x05R\x04ncii\x88\x01\x01\x12J\n" +
	"\aflagged\x18\t \x01(\v2+.osprey.ImageDispatchResults.FlaggedResultsH\x06R\aflagged\x88\x01\x01\x1a\x90\x01\n" +
	"\fAbyssResults\x12\x15\n" +
	"\x03raw\x18\x01 \x01(\fH\x00R\x03raw\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x01R\x05error\x88\x01\x01\x12)\n" +
	"\x0eis_abuse_match\x18\x03 \x01(\bH\x02R\fisAbuseMatch\x88\x01\x01B\x06\n" +
	"\x04_rawB\b\n" +
	"\x06_errorB\x11\n" +
	"\x0f_is_abuse_match\x1a\xde\x01\n" +
	"\vHiveResults\x12\x15\n" +
	"\x03raw\x18\x01 \x01(\fH\x00R\x03raw\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x01R\x05error\x88\x01\x01\x12O\n" +
	"\aclasses\x18\x03 \x03(\v25.osprey.ImageDispatchResults.HiveResults.ClassesEntryR\aclasses\x1a:\n" +
	"\fClassesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01B\x06\n" +
	"\x04_rawB\b\n" +
	"\x06_error\x1au\n" +
	"\rRetinaResults\x12\x15\n" +
	"\x03raw\x18\x01 \x01(\fH\x00R\x03raw\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x01R\x05error\x88\x01\x01\x12\x17\n" +
	"\x04text\x18\x03 \x01(\tH\x02R\x04text\x88\x01\x01B\x06\n" +
	"\x04_rawB\b\n" +
	"\x06_errorB\a\n" +
	"\x05_text\x1a\xba\x01\n" +
	"\x11RetinaHashResults\x12\x15\n" +
	"\x03raw\x18\x01 \x01(\fH\x00R\x03raw\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x01R\x05error\x88\x01\x01\x12\x17\n" +
	"\x04hash\x18\x03 \x01(\tH\x02R\x04hash\x88\x01\x01\x12+\n" +
	"\x0fquality_too_low\x18\x04 \x01(\bH\x03R\rqualityTooLow\x88\x01\x01B\x06\n" +
	"\x04_rawB\b\n" +
	"\x06_errorB\a\n" +
	"\x05_hashB\x12\n" +
	"\x10_quality_too_low\x1a\x84\x01\n" +
	"\x10PrescreenResults\x12\x15\n" +
	"\x03raw\x18\x01 \x01(\fH\x00R\x03raw\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x01R\x05error\x88\x01\x01\x12\x1f\n" +
	"\bdecision\x18\x03 \x01(\tH\x02R\bdecision\x88\x01\x01B\x06\n" +
	"\x04_rawB\b\n" +
	"\x06_errorB\v\n" +
	"\t_decision\x1a\xa3\x01\n" +
	"\vNciiResults\x12\x15\n" +
	"\x03raw\x18\x01 \x01(\fH\x00R\x03raw\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x01R\x05error\x88\x01\x01\x12\x1e\n" +
	"\bis_match\x18\x03 \x01(\bH\x02R\aisMatch\x88\x01\x01\x12\x19\n" +
	"\x05score\x18\x04 \x01(\x01H\x03R\x05score\x88\x01\x01B\x06\n" +
	"\x04_rawB\b\n" +
	"\x06_errorB\v\n" +
	"\t_is_matchB\b\n" +
	"\x06_score\x1a\x94\x03\n" +
	"\x0eFlaggedResults\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01\x12\x1e\n" +
	"\bis_match\x18\x02 \x01(\bH\x01R\aisMatch\x88\x01\x01\x12\x1b\n" +
	"\x06action\x18\x03 \x01(\tH\x02R\x06action\x88\x01\x01\x12&\n" +
	"\faction_level\x18\x04 \x01(\tH\x03R\vactionLevel\x88\x01\x01\x12&\n" +
	"\faction_value\x18\x05 \x01(\tH\x04R\vactionValue\x88\x01\x01\x12(\n" +
	"\ralways_report\x18\x06 \x01(\bH\x05R\falwaysReport\x88\x01\x01\x12%\n" +
	"\vdescription\x18\a \x01(\tH\x06R\vdescription\x88\x01\x01\x12\x19\n" +
	"\x05score\x18\b \x01(\x01H\aR\x05score\x88\x01\x01B\b\n" +
	"\x06_errorB\v\n" +
	"\t_is_matchB\t\n" +
	"\a_actionB\x0f\n" +
	"\r_action_levelB\x0f\n" +
	"\r_action_valueB\x10\n" +
	"\x0e_always_reportB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_scoreB\b\n" +
	"\x06_abyssB\a\n" +
	"\x05_hiveB\t\n" +
	"\a_retinaB\f\n" +
	"\n" +
	"_prescreenB\x0e\n" +
	"\f_retina_hashB\a\n" +
	"\x05_nciiB\n" +
	"\n" +
	"\b_flagged*t\n" +
	"\x12AtprotoSubjectKind\x12\x1d\n" +
	"\x19ATPROTO_SUBJECT_KIND_NONE\x10\x00\x12\x1e\n" +
	"\x1aATPROTO_SUBJECT_KIND_ACTOR\x10\x01\x12\x1f\n" +
	"\x1bATPROTO_SUBJECT_KIND_RECORD\x10\x02*\xf6\x01\n" +
	"\fAtprotoLabel\x12\x16\n" +
	"\x12ATPROTO_LABEL_NONE\x10\x00\x12\x16\n" +
	"\x12ATPROTO_LABEL_SPAM\x10\x01\x12\x16\n" +
	"\x12ATPROTO_LABEL_RUDE\x10\x02\x12\x16\n" +
	"\x12ATPROTO_LABEL_PORN\x10\x03\x12\x18\n" +
	"\x14ATPROTO_LABEL_SEXUAL\x10\x04\x12\x16\n" +
	"\x12ATPROTO_LABEL_WARN\x10\x05\x12\x16\n" +
	"\x12ATPROTO_LABEL_HIDE\x10\x06\x12\x1e\n" +
	"\x1aATPROTO_LABEL_NEEDS_REVIEW\x10\a\x12\x1c\n" +
	"\x18ATPROTO_LABEL_MISLEADING\x10\b*n\n" +
	"\x11AtprotoEffectKind\x12\x1c\n" +
	"\x18ATPROTO_EFFECT_KIND_NONE\x10\x00\x12\x1b\n" +
	"\x17ATPROTO_EFFECT_KIND_ADD\x10\x01\x12\x1e\n" +
	"\x1aATPROTO_EFFECT_KIND_REMOVE\x10\x02*\x93\x04\n" +
	"\fAtprotoEmail\x12\x16\n" +
	"\x12ATPROTO_EMAIL_NONE\x10\x00\x12\x1c\n" +
	"\x18ATPROTO_EMAIL_SPAM_REPLY\x10D\x12 \n" +
	"\x1bATPROTO_EMAIL_SPAM_TAKEDOWN\x10\x85\x02\x12\x1b\n" +
	"\x17ATPROTO_EMAIL_SPAM_FAKE\x10?\x12\x1d\n" +
	"\x18ATPROTO_EMAIL_SPAM_LABEL\x10\xbe\x02\x12&\n" +
	"!ATPROTO_EMAIL_SPAM_LABEL_24_HOURS\x10\xae\x02\x12&\n" +
	"!ATPROTO_EMAIL_SPAM_LABEL_72_HOURS\x10\xb9\x02\x12\x1d\n" +
	"\x18ATPROTO_EMAIL_ID_REQUEST\x10\x99\x02\x12%\n" +
	"!ATPROTO_EMAIL_IMPERSONATION_LABEL\x10\x1f\x12#\n" +
	"\x1eATPROTO_EMAIL_AUTOMOD_TAKEDOWN\x10\xa0\x02\x12\x1f\n" +
	"\x1bATPROTO_EMAIL_REINSTATEMENT\x10<\x12&\n" +
	"\"ATPROTO_EMAIL_THREAT_POST_TAKEDOWN\x10\x1a\x12'\n" +
	"#ATPROTO_EMAIL_PEDO_ACCOUNT_TAKEDOWN\x10+\x12\x1f\n" +
	"\x1aATPROTO_EMAIL_DMS_DISABLED\x10\xa7\x02\x12!\n" +
	"\x1dATPROTO_EMAIL_TOXIC_LIST_HIDE\x103*\xf3\x01\n" +
	"\x11AtprotoReportKind\x12\x1c\n" +
	"\x18ATPROTO_REPORT_KIND_NONE\x10\x00\x12\x1c\n" +
	"\x18ATPROTO_REPORT_KIND_SPAM\x10\x01\x12!\n" +
	"\x1dATPROTO_REPORT_KIND_VIOLATION\x10\x02\x12\"\n" +
	"\x1eATPROTO_REPORT_KIND_MISLEADING\x10\x03\x12\x1e\n" +
	"\x1aATPROTO_REPORT_KIND_SEXUAL\x10\x04\x12\x1c\n" +
	"\x18ATPROTO_REPORT_KIND_RUDE\x10\x05\x12\x1d\n" +
	"\x19ATPROTO_REPORT_KIND_OTHER\x10\x06*o\n" +
	"\tEventKind\x12\x1a\n" +
	"\x16EVENT_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EVENT_KIND_COMMIT\x10\x01\x12\x16\n" +
	"\x12EVENT_KIND_ACCOUNT\x10\x02\x12\x17\n" +
	"\x13EVENT_KIND_IDENTITY\x10\x03*\x8a\x01\n" +
	"\x0fCommitOperation\x12 \n" +
	"\x1cCOMMIT_OPERATION_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17COMMIT_OPERATION_CREATE\x10\x01\x12\x1b\n" +
	"\x17COMMIT_OPERATION_UPDATE\x10\x02\x12\x1b\n" +
	"\x17COMMIT_OPERATION_DELETE\x10\x03Bc\n" +
	"\n" +
	"com.ospreyB\x12OspreyAtprotoProtoP\x01Z\t./;osprey\xa2\x02\x03OXX\xaa\x02\x06Osprey\xca\x02\x06Osprey\xe2\x02\x12Osprey\\GPBMetadata\xea\x02\x06Ospreyb\x06proto3"

var (
	file_osprey_atproto_proto_rawDescOnce sync.Once
	file_osprey_atproto_proto_rawDescData []byte
)

func file_osprey_atproto_proto_rawDescGZIP() []byte {
	file_osprey_atproto_proto_rawDescOnce.Do(func() {
		file_osprey_atproto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_osprey_atproto_proto_rawDesc), len(file_osprey_atproto_proto_rawDesc)))
	})
	return file_osprey_atproto_proto_rawDescData
}

var file_osprey_atproto_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_osprey_atproto_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_osprey_atproto_proto_goTypes = []any{
	(AtprotoSubjectKind)(0),                        // 0: osprey.AtprotoSubjectKind
	(AtprotoLabel)(0),                              // 1: osprey.AtprotoLabel
	(AtprotoEffectKind)(0),                         // 2: osprey.AtprotoEffectKind
	(AtprotoEmail)(0),                              // 3: osprey.AtprotoEmail
	(AtprotoReportKind)(0),                         // 4: osprey.AtprotoReportKind
	(EventKind)(0),                                 // 5: osprey.EventKind
	(CommitOperation)(0),                           // 6: osprey.CommitOperation
	(*OspreyInputEvent)(nil),                       // 7: osprey.OspreyInputEvent
	(*OspreyInputEventData)(nil),                   // 8: osprey.OspreyInputEventData
	(*AtprotoLabelEffect)(nil),                     // 9: osprey.AtprotoLabelEffect
	(*AtprotoTagEffect)(nil),                       // 10: osprey.AtprotoTagEffect
	(*AtprotoTakedownEffect)(nil),                  // 11: osprey.AtprotoTakedownEffect
	(*AtprotoEmailEffect)(nil),                     // 12: osprey.AtprotoEmailEffect
	(*AtprotoCommentEffect)(nil),                   // 13: osprey.AtprotoCommentEffect
	(*AtprotoEscalateEffect)(nil),                  // 14: osprey.AtprotoEscalateEffect
	(*AtprotoAcknowledgeEffect)(nil),               // 15: osprey.AtprotoAcknowledgeEffect
	(*AtprotoReportEffect)(nil),                    // 16: osprey.AtprotoReportEffect
	(*BigQueryFlagEffect)(nil),                     // 17: osprey.BigQueryFlagEffect
	(*ResultEvent)(nil),                            // 18: osprey.ResultEvent
	(*FirehoseEvent)(nil),                          // 19: osprey.FirehoseEvent
	(*Commit)(nil),                                 // 20: osprey.Commit
	(*Cursor)(nil),                                 // 21: osprey.Cursor
	(*ModerationEnrichedFirehoseRecordEvent)(nil),  // 22: osprey.ModerationEnrichedFirehoseRecordEvent
	(*ImageDispatchResults)(nil),                   // 23: osprey.ImageDispatchResults
	nil,                                            // 24: osprey.OspreyInputEventData.SecretDataEntry
	nil,                                            // 25: osprey.ModerationEnrichedFirehoseRecordEvent.ImageResultsEntry
	(*ImageDispatchResults_AbyssResults)(nil),      // 26: osprey.ImageDispatchResults.AbyssResults
	(*ImageDispatchResults_HiveResults)(nil),       // 27: osprey.ImageDispatchResults.HiveResults
	(*ImageDispatchResults_RetinaResults)(nil),     // 28: osprey.ImageDispatchResults.RetinaResults
	(*ImageDispatchResults_RetinaHashResults)(nil), // 29: osprey.ImageDispatchResults.RetinaHashResults
	(*ImageDispatchResults_PrescreenResults)(nil),  // 30: osprey.ImageDispatchResults.PrescreenResults
	(*ImageDispatchResults_NciiResults)(nil),       // 31: osprey.ImageDispatchResults.NciiResults
	(*ImageDispatchResults_FlaggedResults)(nil),    // 32: osprey.ImageDispatchResults.FlaggedResults
	nil,                           // 33: osprey.ImageDispatchResults.HiveResults.ClassesEntry
	(*timestamppb.Timestamp)(nil), // 34: google.protobuf.Timestamp
}
var file_osprey_atproto_proto_depIdxs = []int32{
	8,  // 0: osprey.OspreyInputEvent.data:type_name -> osprey.OspreyInputEventData
	34, // 1: osprey.OspreyInputEvent.send_time:type_name -> google.protobuf.Timestamp
	34, // 2: osprey.OspreyInputEventData.timestamp:type_name -> google.protobuf.Timestamp
	24, // 3: osprey.OspreyInputEventData.secret_data:type_name -> osprey.OspreyInputEventData.SecretDataEntry
	2,  // 4: osprey.AtprotoLabelEffect.effect_kind:type_name -> osprey.AtprotoEffectKind
	0,  // 5: osprey.AtprotoLabelEffect.subject_kind:type_name -> osprey.AtprotoSubjectKind
	1,  // 6: osprey.AtprotoLabelEffect.label:type_name -> osprey.AtprotoLabel
	3,  // 7: osprey.AtprotoLabelEffect.email:type_name -> osprey.AtprotoEmail
	2,  // 8: osprey.AtprotoTagEffect.effect_kind:type_name -> osprey.AtprotoEffectKind
	0,  // 9: osprey.AtprotoTagEffect.subject_kind:type_name -> osprey.AtprotoSubjectKind
	2,  // 10: osprey.AtprotoTakedownEffect.effect_kind:type_name -> osprey.AtprotoEffectKind
	0,  // 11: osprey.AtprotoTakedownEffect.subject_kind:type_name -> osprey.AtprotoSubjectKind
	3,  // 12: osprey.AtprotoTakedownEffect.email:type_name -> osprey.AtprotoEmail
	3,  // 13: osprey.AtprotoEmailEffect.email:type_name -> osprey.AtprotoEmail
	0,  // 14: osprey.AtprotoCommentEffect.subject_kind:type_name -> osprey.AtprotoSubjectKind
	0,  // 15: osprey.AtprotoEscalateEffect.subject_kind:type_name -> osprey.AtprotoSubjectKind
	0,  // 16: osprey.AtprotoAcknowledgeEffect.subject_kind:type_name -> osprey.AtprotoSubjectKind
	0,  // 17: osprey.AtprotoReportEffect.subject_kind:type_name -> osprey.AtprotoSubjectKind
	4,  // 18: osprey.AtprotoReportEffect.report_kind:type_name -> osprey.AtprotoReportKind
	0,  // 19: osprey.BigQueryFlagEffect.subject_kind:type_name -> osprey.AtprotoSubjectKind
	34, // 20: osprey.ResultEvent.send_time:type_name -> google.protobuf.Timestamp
	9,  // 21: osprey.ResultEvent.labels:type_name -> osprey.AtprotoLabelEffect
	10, // 22: osprey.ResultEvent.tags:type_name -> osprey.AtprotoTagEffect
	11, // 23: osprey.ResultEvent.takedowns:type_name -> osprey.AtprotoTakedownEffect
	12, // 24: osprey.ResultEvent.emails:type_name -> osprey.AtprotoEmailEffect
	13, // 25: osprey.ResultEvent.comments:type_name -> osprey.AtprotoCommentEffect
	14, // 26: osprey.ResultEvent.escalations:type_name -> osprey.AtprotoEscalateEffect
	15, // 27: osprey.ResultEvent.acknowledgements:type_name -> osprey.AtprotoAcknowledgeEffect
	16, // 28: osprey.ResultEvent.reports:type_name -> osprey.AtprotoReportEffect
	17, // 29: osprey.ResultEvent.bigqueryFlags:type_name -> osprey.BigQueryFlagEffect
	34, // 30: osprey.FirehoseEvent.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 31: osprey.FirehoseEvent.kind:type_name -> osprey.EventKind
	20, // 32: osprey.FirehoseEvent.commit:type_name -> osprey.Commit
	6,  // 33: osprey.Commit.operation:type_name -> osprey.CommitOperation
	34, // 34: osprey.ModerationEnrichedFirehoseRecordEvent.timestamp:type_name -> google.protobuf.Timestamp
	6,  // 35: osprey.ModerationEnrichedFirehoseRecordEvent.operation:type_name -> osprey.CommitOperation
	25, // 36: osprey.ModerationEnrichedFirehoseRecordEvent.image_results:type_name -> osprey.ModerationEnrichedFirehoseRecordEvent.ImageResultsEntry
	26, // 37: osprey.ImageDispatchResults.abyss:type_name -> osprey.ImageDispatchResults.AbyssResults
	27, // 38: osprey.ImageDispatchResults.hive:type_name -> osprey.ImageDispatchResults.HiveResults
	28, // 39: osprey.ImageDispatchResults.retina:type_name -> osprey.ImageDispatchResults.RetinaResults
	30, // 40: osprey.ImageDispatchResults.prescreen:type_name -> osprey.ImageDispatchResults.PrescreenResults
	29, // 41: osprey.ImageDispatchResults.retina_hash:type_name -> osprey.ImageDispatchResults.RetinaHashResults
	31, // 42: osprey.ImageDispatchResults.ncii:type_name -> osprey.ImageDispatchResults.NciiResults
	32, // 43: osprey.ImageDispatchResults.flagged:type_name -> osprey.ImageDispatchResults.FlaggedResults
	23, // 44: osprey.ModerationEnrichedFirehoseRecordEvent.ImageResultsEntry.value:type_name -> osprey.ImageDispatchResults
	33, // 45: osprey.ImageDispatchResults.HiveResults.classes:type_name -> osprey.ImageDispatchResults.HiveResults.ClassesEntry
	46, // [46:46] is the sub-list for method output_type
	46, // [46:46] is the sub-list for method input_type
	46, // [46:46] is the sub-list for extension type_name
	46, // [46:46] is the sub-list for extension extendee
	0,  // [0:46] is the sub-list for field type_name
}

func init() { file_osprey_atproto_proto_init() }
func file_osprey_atproto_proto_init() {
	if File_osprey_atproto_proto != nil {
		return
	}
	file_osprey_atproto_proto_msgTypes[2].OneofWrappers = []any{}
	file_osprey_atproto_proto_msgTypes[3].OneofWrappers = []any{}
	file_osprey_atproto_proto_msgTypes[4].OneofWrappers = []any{}
	file_osprey_atproto_proto_msgTypes[5].OneofWrappers = []any{}
	file_osprey_atproto_proto_msgTypes[7].OneofWrappers = []any{}
	file_osprey_atproto_proto_msgTypes[8].OneofWrappers = []any{}
	file_osprey_atproto_proto_msgTypes[9].OneofWrappers = []any{}
	file_osprey_atproto_proto_msgTypes[10].OneofWrappers = []any{}
	file_osprey_atproto_proto_msgTypes[15].OneofWrappers = []any{}
	file_osprey_atproto_proto_msgTypes[16].OneofWrappers = []any{}
	file_osprey_atproto_proto_msgTypes[19].OneofWrappers = []any{}
	file_osprey_atproto_proto_msgTypes[20].OneofWrappers = []any{}
	file_osprey_atproto_proto_msgTypes[21].OneofWrappers = []any{}
	file_osprey_atproto_proto_msgTypes[22].OneofWrappers = []any{}
	file_osprey_atproto_proto_msgTypes[23].OneofWrappers = []any{}
	file_osprey_atproto_proto_msgTypes[24].OneofWrappers = []any{}
	file_osprey_atproto_proto_msgTypes[25].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osprey_atproto_proto_rawDesc), len(file_osprey_atproto_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osprey_atproto_proto_goTypes,
		DependencyIndexes: file_osprey_atproto_proto_depIdxs,
		EnumInfos:         file_osprey_atproto_proto_enumTypes,
		MessageInfos:      file_osprey_atproto_proto_msgTypes,
	}.Build()
	File_osprey_atproto_proto = out.File
	file_osprey_atproto_proto_goTypes = nil
	file_osprey_atproto_proto_depIdxs = nil
}
