// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: osprey_atproto.proto

// Implements types for the Bufsteam demo.

package osprey

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AtprotoSubjectKind int32

const (
	AtprotoSubjectKind_ATPROTO_SUBJECT_KIND_NONE   AtprotoSubjectKind = 0
	AtprotoSubjectKind_ATPROTO_SUBJECT_KIND_ACTOR  AtprotoSubjectKind = 1
	AtprotoSubjectKind_ATPROTO_SUBJECT_KIND_RECORD AtprotoSubjectKind = 2
)

// Enum value maps for AtprotoSubjectKind.
var (
	AtprotoSubjectKind_name = map[int32]string{
		0: "ATPROTO_SUBJECT_KIND_NONE",
		1: "ATPROTO_SUBJECT_KIND_ACTOR",
		2: "ATPROTO_SUBJECT_KIND_RECORD",
	}
	AtprotoSubjectKind_value = map[string]int32{
		"ATPROTO_SUBJECT_KIND_NONE":   0,
		"ATPROTO_SUBJECT_KIND_ACTOR":  1,
		"ATPROTO_SUBJECT_KIND_RECORD": 2,
	}
)

func (x AtprotoSubjectKind) Enum() *AtprotoSubjectKind {
	p := new(AtprotoSubjectKind)
	*p = x
	return p
}

func (x AtprotoSubjectKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AtprotoSubjectKind) Descriptor() protoreflect.EnumDescriptor {
	return file_osprey_atproto_proto_enumTypes[0].Descriptor()
}

func (AtprotoSubjectKind) Type() protoreflect.EnumType {
	return &file_osprey_atproto_proto_enumTypes[0]
}

func (x AtprotoSubjectKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AtprotoSubjectKind.Descriptor instead.
func (AtprotoSubjectKind) EnumDescriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{0}
}

type AtprotoLabel int32

const (
	AtprotoLabel_ATPROTO_LABEL_NONE         AtprotoLabel = 0
	AtprotoLabel_ATPROTO_LABEL_SPAM         AtprotoLabel = 1
	AtprotoLabel_ATPROTO_LABEL_RUDE         AtprotoLabel = 2
	AtprotoLabel_ATPROTO_LABEL_PORN         AtprotoLabel = 3
	AtprotoLabel_ATPROTO_LABEL_SEXUAL       AtprotoLabel = 4
	AtprotoLabel_ATPROTO_LABEL_WARN         AtprotoLabel = 5
	AtprotoLabel_ATPROTO_LABEL_HIDE         AtprotoLabel = 6
	AtprotoLabel_ATPROTO_LABEL_NEEDS_REVIEW AtprotoLabel = 7
	AtprotoLabel_ATPROTO_LABEL_MISLEADING   AtprotoLabel = 8
)

// Enum value maps for AtprotoLabel.
var (
	AtprotoLabel_name = map[int32]string{
		0: "ATPROTO_LABEL_NONE",
		1: "ATPROTO_LABEL_SPAM",
		2: "ATPROTO_LABEL_RUDE",
		3: "ATPROTO_LABEL_PORN",
		4: "ATPROTO_LABEL_SEXUAL",
		5: "ATPROTO_LABEL_WARN",
		6: "ATPROTO_LABEL_HIDE",
		7: "ATPROTO_LABEL_NEEDS_REVIEW",
		8: "ATPROTO_LABEL_MISLEADING",
	}
	AtprotoLabel_value = map[string]int32{
		"ATPROTO_LABEL_NONE":         0,
		"ATPROTO_LABEL_SPAM":         1,
		"ATPROTO_LABEL_RUDE":         2,
		"ATPROTO_LABEL_PORN":         3,
		"ATPROTO_LABEL_SEXUAL":       4,
		"ATPROTO_LABEL_WARN":         5,
		"ATPROTO_LABEL_HIDE":         6,
		"ATPROTO_LABEL_NEEDS_REVIEW": 7,
		"ATPROTO_LABEL_MISLEADING":   8,
	}
)

func (x AtprotoLabel) Enum() *AtprotoLabel {
	p := new(AtprotoLabel)
	*p = x
	return p
}

func (x AtprotoLabel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AtprotoLabel) Descriptor() protoreflect.EnumDescriptor {
	return file_osprey_atproto_proto_enumTypes[1].Descriptor()
}

func (AtprotoLabel) Type() protoreflect.EnumType {
	return &file_osprey_atproto_proto_enumTypes[1]
}

func (x AtprotoLabel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AtprotoLabel.Descriptor instead.
func (AtprotoLabel) EnumDescriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{1}
}

type AtprotoEffectKind int32

const (
	AtprotoEffectKind_ATPROTO_EFFECT_KIND_NONE   AtprotoEffectKind = 0
	AtprotoEffectKind_ATPROTO_EFFECT_KIND_ADD    AtprotoEffectKind = 1
	AtprotoEffectKind_ATPROTO_EFFECT_KIND_REMOVE AtprotoEffectKind = 2
)

// Enum value maps for AtprotoEffectKind.
var (
	AtprotoEffectKind_name = map[int32]string{
		0: "ATPROTO_EFFECT_KIND_NONE",
		1: "ATPROTO_EFFECT_KIND_ADD",
		2: "ATPROTO_EFFECT_KIND_REMOVE",
	}
	AtprotoEffectKind_value = map[string]int32{
		"ATPROTO_EFFECT_KIND_NONE":   0,
		"ATPROTO_EFFECT_KIND_ADD":    1,
		"ATPROTO_EFFECT_KIND_REMOVE": 2,
	}
)

func (x AtprotoEffectKind) Enum() *AtprotoEffectKind {
	p := new(AtprotoEffectKind)
	*p = x
	return p
}

func (x AtprotoEffectKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AtprotoEffectKind) Descriptor() protoreflect.EnumDescriptor {
	return file_osprey_atproto_proto_enumTypes[2].Descriptor()
}

func (AtprotoEffectKind) Type() protoreflect.EnumType {
	return &file_osprey_atproto_proto_enumTypes[2]
}

func (x AtprotoEffectKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AtprotoEffectKind.Descriptor instead.
func (AtprotoEffectKind) EnumDescriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{2}
}

type AtprotoEmail int32

const (
	AtprotoEmail_ATPROTO_EMAIL_NONE                  AtprotoEmail = 0
	AtprotoEmail_ATPROTO_EMAIL_SPAM_REPLY            AtprotoEmail = 68
	AtprotoEmail_ATPROTO_EMAIL_SPAM_TAKEDOWN         AtprotoEmail = 261
	AtprotoEmail_ATPROTO_EMAIL_SPAM_FAKE             AtprotoEmail = 63
	AtprotoEmail_ATPROTO_EMAIL_SPAM_LABEL            AtprotoEmail = 318
	AtprotoEmail_ATPROTO_EMAIL_SPAM_LABEL_24_HOURS   AtprotoEmail = 302
	AtprotoEmail_ATPROTO_EMAIL_SPAM_LABEL_72_HOURS   AtprotoEmail = 313
	AtprotoEmail_ATPROTO_EMAIL_ID_REQUEST            AtprotoEmail = 281
	AtprotoEmail_ATPROTO_EMAIL_IMPERSONATION_LABEL   AtprotoEmail = 31
	AtprotoEmail_ATPROTO_EMAIL_AUTOMOD_TAKEDOWN      AtprotoEmail = 288
	AtprotoEmail_ATPROTO_EMAIL_REINSTATEMENT         AtprotoEmail = 60
	AtprotoEmail_ATPROTO_EMAIL_THREAT_POST_TAKEDOWN  AtprotoEmail = 26
	AtprotoEmail_ATPROTO_EMAIL_PEDO_ACCOUNT_TAKEDOWN AtprotoEmail = 43
	AtprotoEmail_ATPROTO_EMAIL_DMS_DISABLED          AtprotoEmail = 295
	AtprotoEmail_ATPROTO_EMAIL_TOXIC_LIST_HIDE       AtprotoEmail = 51
)

// Enum value maps for AtprotoEmail.
var (
	AtprotoEmail_name = map[int32]string{
		0:   "ATPROTO_EMAIL_NONE",
		68:  "ATPROTO_EMAIL_SPAM_REPLY",
		261: "ATPROTO_EMAIL_SPAM_TAKEDOWN",
		63:  "ATPROTO_EMAIL_SPAM_FAKE",
		318: "ATPROTO_EMAIL_SPAM_LABEL",
		302: "ATPROTO_EMAIL_SPAM_LABEL_24_HOURS",
		313: "ATPROTO_EMAIL_SPAM_LABEL_72_HOURS",
		281: "ATPROTO_EMAIL_ID_REQUEST",
		31:  "ATPROTO_EMAIL_IMPERSONATION_LABEL",
		288: "ATPROTO_EMAIL_AUTOMOD_TAKEDOWN",
		60:  "ATPROTO_EMAIL_REINSTATEMENT",
		26:  "ATPROTO_EMAIL_THREAT_POST_TAKEDOWN",
		43:  "ATPROTO_EMAIL_PEDO_ACCOUNT_TAKEDOWN",
		295: "ATPROTO_EMAIL_DMS_DISABLED",
		51:  "ATPROTO_EMAIL_TOXIC_LIST_HIDE",
	}
	AtprotoEmail_value = map[string]int32{
		"ATPROTO_EMAIL_NONE":                  0,
		"ATPROTO_EMAIL_SPAM_REPLY":            68,
		"ATPROTO_EMAIL_SPAM_TAKEDOWN":         261,
		"ATPROTO_EMAIL_SPAM_FAKE":             63,
		"ATPROTO_EMAIL_SPAM_LABEL":            318,
		"ATPROTO_EMAIL_SPAM_LABEL_24_HOURS":   302,
		"ATPROTO_EMAIL_SPAM_LABEL_72_HOURS":   313,
		"ATPROTO_EMAIL_ID_REQUEST":            281,
		"ATPROTO_EMAIL_IMPERSONATION_LABEL":   31,
		"ATPROTO_EMAIL_AUTOMOD_TAKEDOWN":      288,
		"ATPROTO_EMAIL_REINSTATEMENT":         60,
		"ATPROTO_EMAIL_THREAT_POST_TAKEDOWN":  26,
		"ATPROTO_EMAIL_PEDO_ACCOUNT_TAKEDOWN": 43,
		"ATPROTO_EMAIL_DMS_DISABLED":          295,
		"ATPROTO_EMAIL_TOXIC_LIST_HIDE":       51,
	}
)

func (x AtprotoEmail) Enum() *AtprotoEmail {
	p := new(AtprotoEmail)
	*p = x
	return p
}

func (x AtprotoEmail) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AtprotoEmail) Descriptor() protoreflect.EnumDescriptor {
	return file_osprey_atproto_proto_enumTypes[3].Descriptor()
}

func (AtprotoEmail) Type() protoreflect.EnumType {
	return &file_osprey_atproto_proto_enumTypes[3]
}

func (x AtprotoEmail) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AtprotoEmail.Descriptor instead.
func (AtprotoEmail) EnumDescriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{3}
}

type AtprotoReportKind int32

const (
	AtprotoReportKind_ATPROTO_REPORT_KIND_NONE       AtprotoReportKind = 0
	AtprotoReportKind_ATPROTO_REPORT_KIND_SPAM       AtprotoReportKind = 1
	AtprotoReportKind_ATPROTO_REPORT_KIND_VIOLATION  AtprotoReportKind = 2
	AtprotoReportKind_ATPROTO_REPORT_KIND_MISLEADING AtprotoReportKind = 3
	AtprotoReportKind_ATPROTO_REPORT_KIND_SEXUAL     AtprotoReportKind = 4
	AtprotoReportKind_ATPROTO_REPORT_KIND_RUDE       AtprotoReportKind = 5
	AtprotoReportKind_ATPROTO_REPORT_KIND_OTHER      AtprotoReportKind = 6
)

// Enum value maps for AtprotoReportKind.
var (
	AtprotoReportKind_name = map[int32]string{
		0: "ATPROTO_REPORT_KIND_NONE",
		1: "ATPROTO_REPORT_KIND_SPAM",
		2: "ATPROTO_REPORT_KIND_VIOLATION",
		3: "ATPROTO_REPORT_KIND_MISLEADING",
		4: "ATPROTO_REPORT_KIND_SEXUAL",
		5: "ATPROTO_REPORT_KIND_RUDE",
		6: "ATPROTO_REPORT_KIND_OTHER",
	}
	AtprotoReportKind_value = map[string]int32{
		"ATPROTO_REPORT_KIND_NONE":       0,
		"ATPROTO_REPORT_KIND_SPAM":       1,
		"ATPROTO_REPORT_KIND_VIOLATION":  2,
		"ATPROTO_REPORT_KIND_MISLEADING": 3,
		"ATPROTO_REPORT_KIND_SEXUAL":     4,
		"ATPROTO_REPORT_KIND_RUDE":       5,
		"ATPROTO_REPORT_KIND_OTHER":      6,
	}
)

func (x AtprotoReportKind) Enum() *AtprotoReportKind {
	p := new(AtprotoReportKind)
	*p = x
	return p
}

func (x AtprotoReportKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AtprotoReportKind) Descriptor() protoreflect.EnumDescriptor {
	return file_osprey_atproto_proto_enumTypes[4].Descriptor()
}

func (AtprotoReportKind) Type() protoreflect.EnumType {
	return &file_osprey_atproto_proto_enumTypes[4]
}

func (x AtprotoReportKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AtprotoReportKind.Descriptor instead.
func (AtprotoReportKind) EnumDescriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{4}
}

type OspreyInputEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *OspreyInputEventData  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	SendTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OspreyInputEvent) Reset() {
	*x = OspreyInputEvent{}
	mi := &file_osprey_atproto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OspreyInputEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OspreyInputEvent) ProtoMessage() {}

func (x *OspreyInputEvent) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OspreyInputEvent.ProtoReflect.Descriptor instead.
func (*OspreyInputEvent) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{0}
}

func (x *OspreyInputEvent) GetData() *OspreyInputEventData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *OspreyInputEvent) GetSendTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SendTime
	}
	return nil
}

type OspreyInputEventData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionName    string                 `protobuf:"bytes,1,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`
	ActionId      int64                  `protobuf:"varint,2,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SecretData    map[string]string      `protobuf:"bytes,5,rep,name=secret_data,json=secretData,proto3" json:"secret_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Encoding      string                 `protobuf:"bytes,6,opt,name=encoding,proto3" json:"encoding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OspreyInputEventData) Reset() {
	*x = OspreyInputEventData{}
	mi := &file_osprey_atproto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OspreyInputEventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OspreyInputEventData) ProtoMessage() {}

func (x *OspreyInputEventData) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OspreyInputEventData.ProtoReflect.Descriptor instead.
func (*OspreyInputEventData) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{1}
}

func (x *OspreyInputEventData) GetActionName() string {
	if x != nil {
		return x.ActionName
	}
	return ""
}

func (x *OspreyInputEventData) GetActionId() int64 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

func (x *OspreyInputEventData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *OspreyInputEventData) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *OspreyInputEventData) GetSecretData() map[string]string {
	if x != nil {
		return x.SecretData
	}
	return nil
}

func (x *OspreyInputEventData) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

type AtprotoLabelEffect struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EffectKind        AtprotoEffectKind      `protobuf:"varint,1,opt,name=effect_kind,json=effectKind,proto3,enum=osprey.AtprotoEffectKind" json:"effect_kind,omitempty"`
	SubjectKind       AtprotoSubjectKind     `protobuf:"varint,2,opt,name=subject_kind,json=subjectKind,proto3,enum=osprey.AtprotoSubjectKind" json:"subject_kind,omitempty"`
	Label             AtprotoLabel           `protobuf:"varint,3,opt,name=label,proto3,enum=osprey.AtprotoLabel" json:"label,omitempty"`
	Comment           string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	Email             *AtprotoEmail          `protobuf:"varint,5,opt,name=email,proto3,enum=osprey.AtprotoEmail,oneof" json:"email,omitempty"`
	ExpirationInHours *int64                 `protobuf:"varint,6,opt,name=expiration_in_hours,json=expirationInHours,proto3,oneof" json:"expiration_in_hours,omitempty"`
	Rules             []string               `protobuf:"bytes,7,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AtprotoLabelEffect) Reset() {
	*x = AtprotoLabelEffect{}
	mi := &file_osprey_atproto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtprotoLabelEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtprotoLabelEffect) ProtoMessage() {}

func (x *AtprotoLabelEffect) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtprotoLabelEffect.ProtoReflect.Descriptor instead.
func (*AtprotoLabelEffect) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{2}
}

func (x *AtprotoLabelEffect) GetEffectKind() AtprotoEffectKind {
	if x != nil {
		return x.EffectKind
	}
	return AtprotoEffectKind_ATPROTO_EFFECT_KIND_NONE
}

func (x *AtprotoLabelEffect) GetSubjectKind() AtprotoSubjectKind {
	if x != nil {
		return x.SubjectKind
	}
	return AtprotoSubjectKind_ATPROTO_SUBJECT_KIND_NONE
}

func (x *AtprotoLabelEffect) GetLabel() AtprotoLabel {
	if x != nil {
		return x.Label
	}
	return AtprotoLabel_ATPROTO_LABEL_NONE
}

func (x *AtprotoLabelEffect) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *AtprotoLabelEffect) GetEmail() AtprotoEmail {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return AtprotoEmail_ATPROTO_EMAIL_NONE
}

func (x *AtprotoLabelEffect) GetExpirationInHours() int64 {
	if x != nil && x.ExpirationInHours != nil {
		return *x.ExpirationInHours
	}
	return 0
}

func (x *AtprotoLabelEffect) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

type AtprotoTagEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EffectKind    AtprotoEffectKind      `protobuf:"varint,1,opt,name=effect_kind,json=effectKind,proto3,enum=osprey.AtprotoEffectKind" json:"effect_kind,omitempty"`
	SubjectKind   AtprotoSubjectKind     `protobuf:"varint,2,opt,name=subject_kind,json=subjectKind,proto3,enum=osprey.AtprotoSubjectKind" json:"subject_kind,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Comment       *string                `protobuf:"bytes,4,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	Rules         []string               `protobuf:"bytes,5,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtprotoTagEffect) Reset() {
	*x = AtprotoTagEffect{}
	mi := &file_osprey_atproto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtprotoTagEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtprotoTagEffect) ProtoMessage() {}

func (x *AtprotoTagEffect) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtprotoTagEffect.ProtoReflect.Descriptor instead.
func (*AtprotoTagEffect) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{3}
}

func (x *AtprotoTagEffect) GetEffectKind() AtprotoEffectKind {
	if x != nil {
		return x.EffectKind
	}
	return AtprotoEffectKind_ATPROTO_EFFECT_KIND_NONE
}

func (x *AtprotoTagEffect) GetSubjectKind() AtprotoSubjectKind {
	if x != nil {
		return x.SubjectKind
	}
	return AtprotoSubjectKind_ATPROTO_SUBJECT_KIND_NONE
}

func (x *AtprotoTagEffect) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *AtprotoTagEffect) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

func (x *AtprotoTagEffect) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

type AtprotoTakedownEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EffectKind    AtprotoEffectKind      `protobuf:"varint,1,opt,name=effect_kind,json=effectKind,proto3,enum=osprey.AtprotoEffectKind" json:"effect_kind,omitempty"`
	SubjectKind   AtprotoSubjectKind     `protobuf:"varint,2,opt,name=subject_kind,json=subjectKind,proto3,enum=osprey.AtprotoSubjectKind" json:"subject_kind,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	Email         *AtprotoEmail          `protobuf:"varint,5,opt,name=email,proto3,enum=osprey.AtprotoEmail,oneof" json:"email,omitempty"`
	Rules         []string               `protobuf:"bytes,6,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtprotoTakedownEffect) Reset() {
	*x = AtprotoTakedownEffect{}
	mi := &file_osprey_atproto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtprotoTakedownEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtprotoTakedownEffect) ProtoMessage() {}

func (x *AtprotoTakedownEffect) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtprotoTakedownEffect.ProtoReflect.Descriptor instead.
func (*AtprotoTakedownEffect) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{4}
}

func (x *AtprotoTakedownEffect) GetEffectKind() AtprotoEffectKind {
	if x != nil {
		return x.EffectKind
	}
	return AtprotoEffectKind_ATPROTO_EFFECT_KIND_NONE
}

func (x *AtprotoTakedownEffect) GetSubjectKind() AtprotoSubjectKind {
	if x != nil {
		return x.SubjectKind
	}
	return AtprotoSubjectKind_ATPROTO_SUBJECT_KIND_NONE
}

func (x *AtprotoTakedownEffect) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *AtprotoTakedownEffect) GetEmail() AtprotoEmail {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return AtprotoEmail_ATPROTO_EMAIL_NONE
}

func (x *AtprotoTakedownEffect) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

type AtprotoEmailEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         AtprotoEmail           `protobuf:"varint,1,opt,name=email,proto3,enum=osprey.AtprotoEmail" json:"email,omitempty"`
	Comment       *string                `protobuf:"bytes,2,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	Rules         []string               `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtprotoEmailEffect) Reset() {
	*x = AtprotoEmailEffect{}
	mi := &file_osprey_atproto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtprotoEmailEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtprotoEmailEffect) ProtoMessage() {}

func (x *AtprotoEmailEffect) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtprotoEmailEffect.ProtoReflect.Descriptor instead.
func (*AtprotoEmailEffect) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{5}
}

func (x *AtprotoEmailEffect) GetEmail() AtprotoEmail {
	if x != nil {
		return x.Email
	}
	return AtprotoEmail_ATPROTO_EMAIL_NONE
}

func (x *AtprotoEmailEffect) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

func (x *AtprotoEmailEffect) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

type AtprotoCommentEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectKind   AtprotoSubjectKind     `protobuf:"varint,1,opt,name=subject_kind,json=subjectKind,proto3,enum=osprey.AtprotoSubjectKind" json:"subject_kind,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	Rules         []string               `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtprotoCommentEffect) Reset() {
	*x = AtprotoCommentEffect{}
	mi := &file_osprey_atproto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtprotoCommentEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtprotoCommentEffect) ProtoMessage() {}

func (x *AtprotoCommentEffect) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtprotoCommentEffect.ProtoReflect.Descriptor instead.
func (*AtprotoCommentEffect) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{6}
}

func (x *AtprotoCommentEffect) GetSubjectKind() AtprotoSubjectKind {
	if x != nil {
		return x.SubjectKind
	}
	return AtprotoSubjectKind_ATPROTO_SUBJECT_KIND_NONE
}

func (x *AtprotoCommentEffect) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *AtprotoCommentEffect) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

type AtprotoEscalateEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectKind   AtprotoSubjectKind     `protobuf:"varint,1,opt,name=subject_kind,json=subjectKind,proto3,enum=osprey.AtprotoSubjectKind" json:"subject_kind,omitempty"`
	Comment       *string                `protobuf:"bytes,2,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	Rules         []string               `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtprotoEscalateEffect) Reset() {
	*x = AtprotoEscalateEffect{}
	mi := &file_osprey_atproto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtprotoEscalateEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtprotoEscalateEffect) ProtoMessage() {}

func (x *AtprotoEscalateEffect) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtprotoEscalateEffect.ProtoReflect.Descriptor instead.
func (*AtprotoEscalateEffect) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{7}
}

func (x *AtprotoEscalateEffect) GetSubjectKind() AtprotoSubjectKind {
	if x != nil {
		return x.SubjectKind
	}
	return AtprotoSubjectKind_ATPROTO_SUBJECT_KIND_NONE
}

func (x *AtprotoEscalateEffect) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

func (x *AtprotoEscalateEffect) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

type AtprotoAcknowledgeEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectKind   AtprotoSubjectKind     `protobuf:"varint,1,opt,name=subject_kind,json=subjectKind,proto3,enum=osprey.AtprotoSubjectKind" json:"subject_kind,omitempty"`
	Comment       *string                `protobuf:"bytes,2,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	Rules         []string               `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtprotoAcknowledgeEffect) Reset() {
	*x = AtprotoAcknowledgeEffect{}
	mi := &file_osprey_atproto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtprotoAcknowledgeEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtprotoAcknowledgeEffect) ProtoMessage() {}

func (x *AtprotoAcknowledgeEffect) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtprotoAcknowledgeEffect.ProtoReflect.Descriptor instead.
func (*AtprotoAcknowledgeEffect) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{8}
}

func (x *AtprotoAcknowledgeEffect) GetSubjectKind() AtprotoSubjectKind {
	if x != nil {
		return x.SubjectKind
	}
	return AtprotoSubjectKind_ATPROTO_SUBJECT_KIND_NONE
}

func (x *AtprotoAcknowledgeEffect) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

func (x *AtprotoAcknowledgeEffect) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

type AtprotoReportEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectKind   AtprotoSubjectKind     `protobuf:"varint,1,opt,name=subject_kind,json=subjectKind,proto3,enum=osprey.AtprotoSubjectKind" json:"subject_kind,omitempty"`
	ReportKind    AtprotoReportKind      `protobuf:"varint,2,opt,name=report_kind,json=reportKind,proto3,enum=osprey.AtprotoReportKind" json:"report_kind,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	PriorityScore *int64                 `protobuf:"varint,4,opt,name=priority_score,json=priorityScore,proto3,oneof" json:"priority_score,omitempty"`
	Rules         []string               `protobuf:"bytes,5,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtprotoReportEffect) Reset() {
	*x = AtprotoReportEffect{}
	mi := &file_osprey_atproto_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtprotoReportEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtprotoReportEffect) ProtoMessage() {}

func (x *AtprotoReportEffect) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtprotoReportEffect.ProtoReflect.Descriptor instead.
func (*AtprotoReportEffect) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{9}
}

func (x *AtprotoReportEffect) GetSubjectKind() AtprotoSubjectKind {
	if x != nil {
		return x.SubjectKind
	}
	return AtprotoSubjectKind_ATPROTO_SUBJECT_KIND_NONE
}

func (x *AtprotoReportEffect) GetReportKind() AtprotoReportKind {
	if x != nil {
		return x.ReportKind
	}
	return AtprotoReportKind_ATPROTO_REPORT_KIND_NONE
}

func (x *AtprotoReportEffect) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *AtprotoReportEffect) GetPriorityScore() int64 {
	if x != nil && x.PriorityScore != nil {
		return *x.PriorityScore
	}
	return 0
}

func (x *AtprotoReportEffect) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

type BigQueryFlagEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectKind   AtprotoSubjectKind     `protobuf:"varint,1,opt,name=subject_kind,json=subjectKind,proto3,enum=osprey.AtprotoSubjectKind" json:"subject_kind,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Comment       *string                `protobuf:"bytes,3,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	Rules         []string               `protobuf:"bytes,4,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BigQueryFlagEffect) Reset() {
	*x = BigQueryFlagEffect{}
	mi := &file_osprey_atproto_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BigQueryFlagEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BigQueryFlagEffect) ProtoMessage() {}

func (x *BigQueryFlagEffect) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BigQueryFlagEffect.ProtoReflect.Descriptor instead.
func (*BigQueryFlagEffect) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{10}
}

func (x *BigQueryFlagEffect) GetSubjectKind() AtprotoSubjectKind {
	if x != nil {
		return x.SubjectKind
	}
	return AtprotoSubjectKind_ATPROTO_SUBJECT_KIND_NONE
}

func (x *BigQueryFlagEffect) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *BigQueryFlagEffect) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

func (x *BigQueryFlagEffect) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

type ResultEvent struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	SendTime         *timestamppb.Timestamp      `protobuf:"bytes,1,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	ActionName       string                      `protobuf:"bytes,2,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`
	ActionId         int64                       `protobuf:"varint,3,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Did              string                      `protobuf:"bytes,4,opt,name=did,proto3" json:"did,omitempty"`
	Uri              string                      `protobuf:"bytes,5,opt,name=uri,proto3" json:"uri,omitempty"`
	Cid              string                      `protobuf:"bytes,6,opt,name=cid,proto3" json:"cid,omitempty"`
	Data             []byte                      `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	Labels           []*AtprotoLabelEffect       `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty"`
	Tags             []*AtprotoTagEffect         `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	Takedowns        []*AtprotoTakedownEffect    `protobuf:"bytes,10,rep,name=takedowns,proto3" json:"takedowns,omitempty"`
	Emails           []*AtprotoEmailEffect       `protobuf:"bytes,11,rep,name=emails,proto3" json:"emails,omitempty"`
	Comments         []*AtprotoCommentEffect     `protobuf:"bytes,12,rep,name=comments,proto3" json:"comments,omitempty"`
	Escalations      []*AtprotoEscalateEffect    `protobuf:"bytes,13,rep,name=escalations,proto3" json:"escalations,omitempty"`
	Acknowledgements []*AtprotoAcknowledgeEffect `protobuf:"bytes,14,rep,name=acknowledgements,proto3" json:"acknowledgements,omitempty"`
	Reports          []*AtprotoReportEffect      `protobuf:"bytes,15,rep,name=reports,proto3" json:"reports,omitempty"`
	BigqueryFlags    []*BigQueryFlagEffect       `protobuf:"bytes,16,rep,name=bigqueryFlags,proto3" json:"bigqueryFlags,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResultEvent) Reset() {
	*x = ResultEvent{}
	mi := &file_osprey_atproto_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultEvent) ProtoMessage() {}

func (x *ResultEvent) ProtoReflect() protoreflect.Message {
	mi := &file_osprey_atproto_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultEvent.ProtoReflect.Descriptor instead.
func (*ResultEvent) Descriptor() ([]byte, []int) {
	return file_osprey_atproto_proto_rawDescGZIP(), []int{11}
}

func (x *ResultEvent) GetSendTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SendTime
	}
	return nil
}

func (x *ResultEvent) GetActionName() string {
	if x != nil {
		return x.ActionName
	}
	return ""
}

func (x *ResultEvent) GetActionId() int64 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

func (x *ResultEvent) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *ResultEvent) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ResultEvent) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ResultEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ResultEvent) GetLabels() []*AtprotoLabelEffect {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ResultEvent) GetTags() []*AtprotoTagEffect {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ResultEvent) GetTakedowns() []*AtprotoTakedownEffect {
	if x != nil {
		return x.Takedowns
	}
	return nil
}

func (x *ResultEvent) GetEmails() []*AtprotoEmailEffect {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *ResultEvent) GetComments() []*AtprotoCommentEffect {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *ResultEvent) GetEscalations() []*AtprotoEscalateEffect {
	if x != nil {
		return x.Escalations
	}
	return nil
}

func (x *ResultEvent) GetAcknowledgements() []*AtprotoAcknowledgeEffect {
	if x != nil {
		return x.Acknowledgements
	}
	return nil
}

func (x *ResultEvent) GetReports() []*AtprotoReportEffect {
	if x != nil {
		return x.Reports
	}
	return nil
}

func (x *ResultEvent) GetBigqueryFlags() []*BigQueryFlagEffect {
	if x != nil {
		return x.BigqueryFlags
	}
	return nil
}

var File_osprey_atproto_proto protoreflect.FileDescriptor

const file_osprey_atproto_proto_rawDesc = "" +
	"\n" +
	"\x14osprey_atproto.proto\x12\x06osprey\x1a\x1fgoogle/protobuf/timestamp.proto\"}\n" +
	"\x10OspreyInputEvent\x120\n" +
	"\x04data\x18\x01 \x01(\v2\x1c.osprey.OspreyInputEventDataR\x04data\x127\n" +
	"\tsend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bsendTime\"\xcc\x02\n" +
	"\x14OspreyInputEventData\x12\x1f\n" +
	"\vaction_name\x18\x01 \x01(\tR\n" +
	"actionName\x12\x1b\n" +
	"\taction_id\x18\x02 \x01(\x03R\bactionId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12M\n" +
	"\vsecret_data\x18\x05 \x03(\v2,.osprey.OspreyInputEventData.SecretDataEntryR\n" +
	"secretData\x12\x1a\n" +
	"\bencoding\x18\x06 \x01(\tR\bencoding\x1a=\n" +
	"\x0fSecretDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf3\x02\n" +
	"\x12AtprotoLabelEffect\x12:\n" +
	"\veffect_kind\x18\x01 \x01(\x0e2\x19.osprey.AtprotoEffectKindR\n" +
	"effectKind\x12=\n" +
	"\fsubject_kind\x18\x02 \x01(\x0e2\x1a.osprey.AtprotoSubjectKindR\vsubjectKind\x12*\n" +
	"\x05label\x18\x03 \x01(\x0e2\x14.osprey.AtprotoLabelR\x05label\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12/\n" +
	"\x05email\x18\x05 \x01(\x0e2\x14.osprey.AtprotoEmailH\x00R\x05email\x88\x01\x01\x123\n" +
	"\x13expiration_in_hours\x18\x06 \x01(\x03H\x01R\x11expirationInHours\x88\x01\x01\x12\x14\n" +
	"\x05rules\x18\a \x03(\tR\x05rulesB\b\n" +
	"\x06_emailB\x16\n" +
	"\x14_expiration_in_hours\"\xe0\x01\n" +
	"\x10AtprotoTagEffect\x12:\n" +
	"\veffect_kind\x18\x01 \x01(\x0e2\x19.osprey.AtprotoEffectKindR\n" +
	"effectKind\x12=\n" +
	"\fsubject_kind\x18\x02 \x01(\x0e2\x1a.osprey.AtprotoSubjectKindR\vsubjectKind\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12\x1d\n" +
	"\acomment\x18\x04 \x01(\tH\x00R\acomment\x88\x01\x01\x12\x14\n" +
	"\x05rules\x18\x05 \x03(\tR\x05rulesB\n" +
	"\n" +
	"\b_comment\"\xfd\x01\n" +
	"\x15AtprotoTakedownEffect\x12:\n" +
	"\veffect_kind\x18\x01 \x01(\x0e2\x19.osprey.AtprotoEffectKindR\n" +
	"effectKind\x12=\n" +
	"\fsubject_kind\x18\x02 \x01(\x0e2\x1a.osprey.AtprotoSubjectKindR\vsubjectKind\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12/\n" +
	"\x05email\x18\x05 \x01(\x0e2\x14.osprey.AtprotoEmailH\x00R\x05email\x88\x01\x01\x12\x14\n" +
	"\x05rules\x18\x06 \x03(\tR\x05rulesB\b\n" +
	"\x06_email\"\x81\x01\n" +
	"\x12AtprotoEmailEffect\x12*\n" +
	"\x05email\x18\x01 \x01(\x0e2\x14.osprey.AtprotoEmailR\x05email\x12\x1d\n" +
	"\acomment\x18\x02 \x01(\tH\x00R\acomment\x88\x01\x01\x12\x14\n" +
	"\x05rules\x18\x03 \x03(\tR\x05rulesB\n" +
	"\n" +
	"\b_comment\"\x85\x01\n" +
	"\x14AtprotoCommentEffect\x12=\n" +
	"\fsubject_kind\x18\x01 \x01(\x0e2\x1a.osprey.AtprotoSubjectKindR\vsubjectKind\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12\x14\n" +
	"\x05rules\x18\x03 \x03(\tR\x05rules\"\x97\x01\n" +
	"\x15AtprotoEscalateEffect\x12=\n" +
	"\fsubject_kind\x18\x01 \x01(\x0e2\x1a.osprey.AtprotoSubjectKindR\vsubjectKind\x12\x1d\n" +
	"\acomment\x18\x02 \x01(\tH\x00R\acomment\x88\x01\x01\x12\x14\n" +
	"\x05rules\x18\x03 \x03(\tR\x05rulesB\n" +
	"\n" +
	"\b_comment\"\x9a\x01\n" +
	"\x18AtprotoAcknowledgeEffect\x12=\n" +
	"\fsubject_kind\x18\x01 \x01(\x0e2\x1a.osprey.AtprotoSubjectKindR\vsubjectKind\x12\x1d\n" +
	"\acomment\x18\x02 \x01(\tH\x00R\acomment\x88\x01\x01\x12\x14\n" +
	"\x05rules\x18\x03 \x03(\tR\x05rulesB\n" +
	"\n" +
	"\b_comment\"\xff\x01\n" +
	"\x13AtprotoReportEffect\x12=\n" +
	"\fsubject_kind\x18\x01 \x01(\x0e2\x1a.osprey.AtprotoSubjectKindR\vsubjectKind\x12:\n" +
	"\vreport_kind\x18\x02 \x01(\x0e2\x19.osprey.AtprotoReportKindR\n" +
	"reportKind\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x12*\n" +
	"\x0epriority_score\x18\x04 \x01(\x03H\x00R\rpriorityScore\x88\x01\x01\x12\x14\n" +
	"\x05rules\x18\x05 \x03(\tR\x05rulesB\x11\n" +
	"\x0f_priority_score\"\xa6\x01\n" +
	"\x12BigQueryFlagEffect\x12=\n" +
	"\fsubject_kind\x18\x01 \x01(\x0e2\x1a.osprey.AtprotoSubjectKindR\vsubjectKind\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x1d\n" +
	"\acomment\x18\x03 \x01(\tH\x00R\acomment\x88\x01\x01\x12\x14\n" +
	"\x05rules\x18\x04 \x03(\tR\x05rulesB\n" +
	"\n" +
	"\b_comment\"\xe3\x05\n" +
	"\vResultEvent\x127\n" +
	"\tsend_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bsendTime\x12\x1f\n" +
	"\vaction_name\x18\x02 \x01(\tR\n" +
	"actionName\x12\x1b\n" +
	"\taction_id\x18\x03 \x01(\x03R\bactionId\x12\x10\n" +
	"\x03did\x18\x04 \x01(\tR\x03did\x12\x10\n" +
	"\x03uri\x18\x05 \x01(\tR\x03uri\x12\x10\n" +
	"\x03cid\x18\x06 \x01(\tR\x03cid\x12\x12\n" +
	"\x04data\x18\a \x01(\fR\x04data\x122\n" +
	"\x06labels\x18\b \x03(\v2\x1a.osprey.AtprotoLabelEffectR\x06labels\x12,\n" +
	"\x04tags\x18\t \x03(\v2\x18.osprey.AtprotoTagEffectR\x04tags\x12;\n" +
	"\ttakedowns\x18\n" +
	" \x03(\v2\x1d.osprey.AtprotoTakedownEffectR\ttakedowns\x122\n" +
	"\x06emails\x18\v \x03(\v2\x1a.osprey.AtprotoEmailEffectR\x06emails\x128\n" +
	"\bcomments\x18\f \x03(\v2\x1c.osprey.AtprotoCommentEffectR\bcomments\x12?\n" +
	"\vescalations\x18\r \x03(\v2\x1d.osprey.AtprotoEscalateEffectR\vescalations\x12L\n" +
	"\x10acknowledgements\x18\x0e \x03(\v2 .osprey.AtprotoAcknowledgeEffectR\x10acknowledgements\x125\n" +
	"\areports\x18\x0f \x03(\v2\x1b.osprey.AtprotoReportEffectR\areports\x12@\n" +
	"\rbigqueryFlags\x18\x10 \x03(\v2\x1a.osprey.BigQueryFlagEffectR\rbigqueryFlags*t\n" +
	"\x12AtprotoSubjectKind\x12\x1d\n" +
	"\x19ATPROTO_SUBJECT_KIND_NONE\x10\x00\x12\x1e\n" +
	"\x1aATPROTO_SUBJECT_KIND_ACTOR\x10\x01\x12\x1f\n" +
	"\x1bATPROTO_SUBJECT_KIND_RECORD\x10\x02*\xf6\x01\n" +
	"\fAtprotoLabel\x12\x16\n" +
	"\x12ATPROTO_LABEL_NONE\x10\x00\x12\x16\n" +
	"\x12ATPROTO_LABEL_SPAM\x10\x01\x12\x16\n" +
	"\x12ATPROTO_LABEL_RUDE\x10\x02\x12\x16\n" +
	"\x12ATPROTO_LABEL_PORN\x10\x03\x12\x18\n" +
	"\x14ATPROTO_LABEL_SEXUAL\x10\x04\x12\x16\n" +
	"\x12ATPROTO_LABEL_WARN\x10\x05\x12\x16\n" +
	"\x12ATPROTO_LABEL_HIDE\x10\x06\x12\x1e\n" +
	"\x1aATPROTO_LABEL_NEEDS_REVIEW\x10\a\x12\x1c\n" +
	"\x18ATPROTO_LABEL_MISLEADING\x10\b*n\n" +
	"\x11AtprotoEffectKind\x12\x1c\n" +
	"\x18ATPROTO_EFFECT_KIND_NONE\x10\x00\x12\x1b\n" +
	"\x17ATPROTO_EFFECT_KIND_ADD\x10\x01\x12\x1e\n" +
	"\x1aATPROTO_EFFECT_KIND_REMOVE\x10\x02*\x93\x04\n" +
	"\fAtprotoEmail\x12\x16\n" +
	"\x12ATPROTO_EMAIL_NONE\x10\x00\x12\x1c\n" +
	"\x18ATPROTO_EMAIL_SPAM_REPLY\x10D\x12 \n" +
	"\x1bATPROTO_EMAIL_SPAM_TAKEDOWN\x10\x85\x02\x12\x1b\n" +
	"\x17ATPROTO_EMAIL_SPAM_FAKE\x10?\x12\x1d\n" +
	"\x18ATPROTO_EMAIL_SPAM_LABEL\x10\xbe\x02\x12&\n" +
	"!ATPROTO_EMAIL_SPAM_LABEL_24_HOURS\x10\xae\x02\x12&\n" +
	"!ATPROTO_EMAIL_SPAM_LABEL_72_HOURS\x10\xb9\x02\x12\x1d\n" +
	"\x18ATPROTO_EMAIL_ID_REQUEST\x10\x99\x02\x12%\n" +
	"!ATPROTO_EMAIL_IMPERSONATION_LABEL\x10\x1f\x12#\n" +
	"\x1eATPROTO_EMAIL_AUTOMOD_TAKEDOWN\x10\xa0\x02\x12\x1f\n" +
	"\x1bATPROTO_EMAIL_REINSTATEMENT\x10<\x12&\n" +
	"\"ATPROTO_EMAIL_THREAT_POST_TAKEDOWN\x10\x1a\x12'\n" +
	"#ATPROTO_EMAIL_PEDO_ACCOUNT_TAKEDOWN\x10+\x12\x1f\n" +
	"\x1aATPROTO_EMAIL_DMS_DISABLED\x10\xa7\x02\x12!\n" +
	"\x1dATPROTO_EMAIL_TOXIC_LIST_HIDE\x103*\xf3\x01\n" +
	"\x11AtprotoReportKind\x12\x1c\n" +
	"\x18ATPROTO_REPORT_KIND_NONE\x10\x00\x12\x1c\n" +
	"\x18ATPROTO_REPORT_KIND_SPAM\x10\x01\x12!\n" +
	"\x1dATPROTO_REPORT_KIND_VIOLATION\x10\x02\x12\"\n" +
	"\x1eATPROTO_REPORT_KIND_MISLEADING\x10\x03\x12\x1e\n" +
	"\x1aATPROTO_REPORT_KIND_SEXUAL\x10\x04\x12\x1c\n" +
	"\x18ATPROTO_REPORT_KIND_RUDE\x10\x05\x12\x1d\n" +
	"\x19ATPROTO_REPORT_KIND_OTHER\x10\x06Bc\n" +
	"\n" +
	"com.ospreyB\x12OspreyAtprotoProtoP\x01Z\t./;osprey\xa2\x02\x03OXX\xaa\x02\x06Osprey\xca\x02\x06Osprey\xe2\x02\x12Osprey\\GPBMetadata\xea\x02\x06Ospreyb\x06proto3"

var (
	file_osprey_atproto_proto_rawDescOnce sync.Once
	file_osprey_atproto_proto_rawDescData []byte
)

func file_osprey_atproto_proto_rawDescGZIP() []byte {
	file_osprey_atproto_proto_rawDescOnce.Do(func() {
		file_osprey_atproto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_osprey_atproto_proto_rawDesc), len(file_osprey_atproto_proto_rawDesc)))
	})
	return file_osprey_atproto_proto_rawDescData
}

var file_osprey_atproto_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_osprey_atproto_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_osprey_atproto_proto_goTypes = []any{
	(AtprotoSubjectKind)(0),          // 0: osprey.AtprotoSubjectKind
	(AtprotoLabel)(0),                // 1: osprey.AtprotoLabel
	(AtprotoEffectKind)(0),           // 2: osprey.AtprotoEffectKind
	(AtprotoEmail)(0),                // 3: osprey.AtprotoEmail
	(AtprotoReportKind)(0),           // 4: osprey.AtprotoReportKind
	(*OspreyInputEvent)(nil),         // 5: osprey.OspreyInputEvent
	(*OspreyInputEventData)(nil),     // 6: osprey.OspreyInputEventData
	(*AtprotoLabelEffect)(nil),       // 7: osprey.AtprotoLabelEffect
	(*AtprotoTagEffect)(nil),         // 8: osprey.AtprotoTagEffect
	(*AtprotoTakedownEffect)(nil),    // 9: osprey.AtprotoTakedownEffect
	(*AtprotoEmailEffect)(nil),       // 10: osprey.AtprotoEmailEffect
	(*AtprotoCommentEffect)(nil),     // 11: osprey.AtprotoCommentEffect
	(*AtprotoEscalateEffect)(nil),    // 12: osprey.AtprotoEscalateEffect
	(*AtprotoAcknowledgeEffect)(nil), // 13: osprey.AtprotoAcknowledgeEffect
	(*AtprotoReportEffect)(nil),      // 14: osprey.AtprotoReportEffect
	(*BigQueryFlagEffect)(nil),       // 15: osprey.BigQueryFlagEffect
	(*ResultEvent)(nil),              // 16: osprey.ResultEvent
	nil,                              // 17: osprey.OspreyInputEventData.SecretDataEntry
	(*timestamppb.Timestamp)(nil),    // 18: google.protobuf.Timestamp
}
var file_osprey_atproto_proto_depIdxs = []int32{
	6,  // 0: osprey.OspreyInputEvent.data:type_name -> osprey.OspreyInputEventData
	18, // 1: osprey.OspreyInputEvent.send_time:type_name -> google.protobuf.Timestamp
	18, // 2: osprey.OspreyInputEventData.timestamp:type_name -> google.protobuf.Timestamp
	17, // 3: osprey.OspreyInputEventData.secret_data:type_name -> osprey.OspreyInputEventData.SecretDataEntry
	2,  // 4: osprey.AtprotoLabelEffect.effect_kind:type_name -> osprey.AtprotoEffectKind
	0,  // 5: osprey.AtprotoLabelEffect.subject_kind:type_name -> osprey.AtprotoSubjectKind
	1,  // 6: osprey.AtprotoLabelEffect.label:type_name -> osprey.AtprotoLabel
	3,  // 7: osprey.AtprotoLabelEffect.email:type_name -> osprey.AtprotoEmail
	2,  // 8: osprey.AtprotoTagEffect.effect_kind:type_name -> osprey.AtprotoEffectKind
	0,  // 9: osprey.AtprotoTagEffect.subject_kind:type_name -> osprey.AtprotoSubjectKind
	2,  // 10: osprey.AtprotoTakedownEffect.effect_kind:type_name -> osprey.AtprotoEffectKind
	0,  // 11: osprey.AtprotoTakedownEffect.subject_kind:type_name -> osprey.AtprotoSubjectKind
	3,  // 12: osprey.AtprotoTakedownEffect.email:type_name -> osprey.AtprotoEmail
	3,  // 13: osprey.AtprotoEmailEffect.email:type_name -> osprey.AtprotoEmail
	0,  // 14: osprey.AtprotoCommentEffect.subject_kind:type_name -> osprey.AtprotoSubjectKind
	0,  // 15: osprey.AtprotoEscalateEffect.subject_kind:type_name -> osprey.AtprotoSubjectKind
	0,  // 16: osprey.AtprotoAcknowledgeEffect.subject_kind:type_name -> osprey.AtprotoSubjectKind
	0,  // 17: osprey.AtprotoReportEffect.subject_kind:type_name -> osprey.AtprotoSubjectKind
	4,  // 18: osprey.AtprotoReportEffect.report_kind:type_name -> osprey.AtprotoReportKind
	0,  // 19: osprey.BigQueryFlagEffect.subject_kind:type_name -> osprey.AtprotoSubjectKind
	18, // 20: osprey.ResultEvent.send_time:type_name -> google.protobuf.Timestamp
	7,  // 21: osprey.ResultEvent.labels:type_name -> osprey.AtprotoLabelEffect
	8,  // 22: osprey.ResultEvent.tags:type_name -> osprey.AtprotoTagEffect
	9,  // 23: osprey.ResultEvent.takedowns:type_name -> osprey.AtprotoTakedownEffect
	10, // 24: osprey.ResultEvent.emails:type_name -> osprey.AtprotoEmailEffect
	11, // 25: osprey.ResultEvent.comments:type_name -> osprey.AtprotoCommentEffect
	12, // 26: osprey.ResultEvent.escalations:type_name -> osprey.AtprotoEscalateEffect
	13, // 27: osprey.ResultEvent.acknowledgements:type_name -> osprey.AtprotoAcknowledgeEffect
	14, // 28: osprey.ResultEvent.reports:type_name -> osprey.AtprotoReportEffect
	15, // 29: osprey.ResultEvent.bigqueryFlags:type_name -> osprey.BigQueryFlagEffect
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_osprey_atproto_proto_init() }
func file_osprey_atproto_proto_init() {
	if File_osprey_atproto_proto != nil {
		return
	}
	file_osprey_atproto_proto_msgTypes[2].OneofWrappers = []any{}
	file_osprey_atproto_proto_msgTypes[3].OneofWrappers = []any{}
	file_osprey_atproto_proto_msgTypes[4].OneofWrappers = []any{}
	file_osprey_atproto_proto_msgTypes[5].OneofWrappers = []any{}
	file_osprey_atproto_proto_msgTypes[7].OneofWrappers = []any{}
	file_osprey_atproto_proto_msgTypes[8].OneofWrappers = []any{}
	file_osprey_atproto_proto_msgTypes[9].OneofWrappers = []any{}
	file_osprey_atproto_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osprey_atproto_proto_rawDesc), len(file_osprey_atproto_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osprey_atproto_proto_goTypes,
		DependencyIndexes: file_osprey_atproto_proto_depIdxs,
		EnumInfos:         file_osprey_atproto_proto_enumTypes,
		MessageInfos:      file_osprey_atproto_proto_msgTypes,
	}.Build()
	File_osprey_atproto_proto = out.File
	file_osprey_atproto_proto_goTypes = nil
	file_osprey_atproto_proto_depIdxs = nil
}
